### ISSUE TITLE
Autocomplete does not support variant specific functions

### ISSUE THREAD

**Issue by jonchan51** [source-academy/cadet-frontend#1063]
Variant-specific functions, such as `concurrent_execute` for Source 3 Concurrent and `require` for Source 3 Non-Det are not showing as prompts for autocompletion.

![image](https://user-images.githubusercontent.com/32188705/79043359-4882e100-7c31-11ea-96ce-f8a46ad3842c.png)

Possible fix but not sure whether it'll work with the other variants. Works with Source 3 Concurrent. 
The relevant file is `src/sagas/workspaces.ts`

**Comment by martin-henz** [comment]
This works now!
