### ISSUE TITLE
Strange grey line in the REPL textbox on large screens?

### ISSUE THREAD

**Issue by btzy** [source-academy/cadet-frontend#1119]
There is a strange grey line on the right side of the REPL textbox if a sufficiently large screen is used.  This line doesn't seem to do anything, and text can go past the line.  Seems like an Ace editor thing, but is it necessary?

![image](https://user-images.githubusercontent.com/6948096/82039526-b1012a00-96d7-11ea-9c2c-96defec88998.png)

![image](https://user-images.githubusercontent.com/6948096/82039573-c4ac9080-96d7-11ea-9cf4-e5428a834d8f.png)

**Comment by seanlowjk** [comment]
It was mainly for the editor. A soft limit for 01S students to adhere to the 80 character limit so avengers can tell them as such. 

However, it is not necessary for the REPL as you kindly pointed out too! 

Will do a quick fix!
