### ISSUE TITLE
Env Viz and Inspector: gutter click leads to spurious error messages

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#1126]
Example 1:

<img width="630" alt="Screenshot 2020-05-19 at 4 30 11 PM" src="https://user-images.githubusercontent.com/30220768/82303823-0c8c2a00-99ee-11ea-93aa-96bf9ed2d1b0.png">

Example 2:

<img width="630" alt="Screenshot 2020-05-19 at 4 31 26 PM" src="https://user-images.githubusercontent.com/30220768/82303982-48bf8a80-99ee-11ea-9906-9406f9596728.png">

this followed by a removal of Line 3 leads to:

<img width="729" alt="Screenshot 2020-05-19 at 4 31 50 PM" src="https://user-images.githubusercontent.com/30220768/82304018-56751000-99ee-11ea-9d2e-2b2515bba583.png">

**Comment by martin-henz** [comment]
Background: gutter click is implemented by inserting ``debugger;`` in the program.

**Comment by blackening** [comment]
Breakpoint also does not move when the code is edited, allowing cases such as the following:
![image](https://user-images.githubusercontent.com/1753927/86430509-0dbab180-bd25-11ea-9e0e-0863e4dd11d9.png)

**Comment by martin-henz** [comment]
I'm referring to the telegram discussion in SA 2021 INSPECT about this, from May 19, 2020.

The most economical solution is the following, suggested by @openorclose :

(1) The frontend keeps track of gutter clicks and marks them with red dots, but does not insert any "debugger;" into the program.
(2) "Run" parses the program in a loop:
* the program as is
* the program with the first breakpoint added as "debugger;"
* the program with the second breakpoint added as "debugger;"
etc
The first time the parser chokes on the program, we know that the "debugger;" statement was in the wrong place. Then we issue an error message:
"Breakpoint in line xxx is not at the beginning of a statement."

If there is no line where the breakpoint can be inserted (the breakpoint exceeds the end of the program), the frontend will issue the same error message.

**Comment by podocarp** [comment]
The breakpoints are taken directly from the ace editor, so moving breakpoints is going to be a bit complicated. Best case is they implement that feature on their side. Otherwise we will have to listen on edits made in the editor and move the breakpoints. I think a separate issue can be made for that.

**Comment by martin-henz** [comment]
Yes, that's right. We can live with breakpoints fixed to specific line numbers. It's what-you-see-is-what-you-get. Users will just have to move the breakpoints after inserting lines. No big deal. Good to keep the implementation simple.
