### ISSUE TITLE
Game Dev: Display published Story XML

### ISSUE THREAD

**Issue by jetkan-yk** [source-academy/cadet-frontend#1131]
## Problem
 `Load XML files from AWS` button not working (function not implemented).

It should import all published Story XML from the [AWS S3](https://source-academy-assets.s3-ap-southeast-1.amazonaws.com/stories/master.story.xml).

> The XML files hosted on the AWS S3 are made publicly read-only and is the single source of truth for all Story XML files to be rendered by the game engine.

![image](https://user-images.githubusercontent.com/36299141/82410113-ce504280-9aa1-11ea-9890-efea1e12ca33.png)

## Suggestion
Remove the button and create a separate tab to view all published Story XML instead.

Mockup Design:

![image](https://user-images.githubusercontent.com/36299141/82411652-be862d80-9aa4-11ea-9d4c-dde4dddac0f3.png)

**Comment by martin-henz** [comment]
You say:

**It should import all published Story XML from the AWS S3.**

Why only the published Story XML files?

The staff workflow will be:

(1) Cook up a new story in a local XML file
(2) Upload the story without publishing it
(3) Play with the system, different game states etc (possibly repeat (1) and (2))
(4) Publish the new story

**Comment by jetkan-yk** [comment]
> Why only the published Story XML files?

Not just the published files. There will be **2 tables** in the Game Dev page: 
- **Collaborative draft table**
- **Published table**

### Collaborative Draft Table
Story writers can **upload, play and download** Story XML files on this table.
This will replace our current workflow of writers collaborating on a [bitbucket repo](https://bitbucket.org/cs1101s/cs1101s_story_1920_sem1/src/master/).

### Published Table
Story writers can **play and download** Story XML files that have been published to the AWS S3.
Writers who want to refer to the published XML codes will find this table useful.

**Comment by jetkan-yk** [comment]
## Story authoring & publishing
There are 2 roles in the workflow: story writer and story publisher

### Story writer workflow
(1) Cook up a new story in a local XML file
(2) Upload the story (to the draft table) without publishing it
(3) Play with the system, different game states etc (possibly repeat (1) and (2))
(4) Notify the story publisher of the new story

### Story publisher workflow:
(1) Proofread the new story from the draft table
(2) Request for edits from writer (if applicable)
(3) Download the new story from the draft table
(4) Publish the new story to AWS S3*

**Comment by martin-henz** [comment]
Let's keep things simple.

The user should not need to think in terms of different tables.

There is no need to distinguish the roles of writer and publisher.

It should be up to the story authors to use whatever tools they have to work on the stories. I don't think our backend should replace such tools. We should use version control or whatever collaboration we want to.

We should focus on the objective at hand, and not take on tangential features such as version control or workflow management.

The objective is very simple: We should let the story authors play and test new stories before they are published, using a game state that they can define.

**Comment by martin-henz** [comment]
The use just needs to see one flag for a story: published/not published

Once the user is happy with the not published new story, he will publish it.

This can be a collective decision: Multiple users can take a look and play, and collectively decide to publish. They can use whatever way they find convenient to author the stories, version control or whatever. Our system does not need to be burdened by the decision process or any version control requirements.

**Comment by jetkan-yk** [comment]
I agree with keeping it simple.

If we want to integrate the publish function, shall we make it like Ground Control?

![image](https://user-images.githubusercontent.com/36299141/82447112-5ce0b600-9ada-11ea-9ebd-b66e4d100c59.png)
(Snapshot from Ground Control)

**Comment by martin-henz** [comment]
We could make it even part of Ground Control, using the same table.

Can we add a column "Number" in Ground Control to show the number tag of the assessment?

Story files would also have a "Number". No Title. They would have category "Story". No open or close date, but the possibility of "Publish" and "Delete". I think it makes sense to display the stories in the same table so that the game story author sees the matching assessment. Sorting according to "Number" will make them pair up nicely.

**Comment by jetkan-yk** [comment]
Since the features of Ground Control and Game Dev are highly overlapping, I think it makes sense to intergrate the Game Dev into Ground Control. 

The staffs can choose to upload Assessment (Mission, Contest) XML or Story XML from the dropzone. On the Ground Control table, each XML item has:
- ID as the primary identifying key (filename, e.g. M2.xml or M2-story.xml)
- short description (optional)
- category (Mission/Quest/Contest/Path/Story)
- open date & time
- close date & time
- publish button
- delete button
- download button

When the user clicks an item on the table, if it is an Assessment XML, the SA will load the Assessment on playground. Otherwise if it is a Story XML, a pop-up will appear for the staff to upload their preferred game state, then play the story in game.

![image](https://user-images.githubusercontent.com/36299141/82535760-ebf0db00-9b79-11ea-8db7-231c12206cc2.png)

**Comment by jetkan-yk** [comment]
For the backend implementation, please refer to discussion here: https://github.com/source-academy/cadet/issues/592

**Comment by jetkan-yk** [comment]
The decisions for this issue is documented in this wiki page: https://github.com/source-academy/cadet-frontend/wiki/Design-Decision:-Ground-Control,-Assessment-&-Story-XML-database,-Game-Storyline

**Comment by anthony-halim** [comment]
Closing issue as the current approach for Story Simulator as well as story writing has changed since this discussion.
