### ISSUE TITLE
Get rid of jQuery

### ISSUE THREAD

**Issue by angelsl** [source-academy/cadet-frontend#1136]
Seems like jQuery was brought in when the story components were [copy-pasted from the old source-academy2](https://github.com/source-academy/cadet-frontend/commit/bd58aa8366b8a2345bb659c34248638b8c706537).

https://github.com/source-academy/cadet-frontend/blob/sa_2021/src/components/academy/game/story-manager/story-manager.js#L125

https://github.com/source-academy/cadet-frontend/blob/sa_2021/public/index.html#L8

Should really get rid of it, but that means we need to parse XML in some other way.

Alternatively, could consider converting the XML to a new JSON format.

**Comment by JingYenLoh** [comment]
> Should really get rid of it, but that means we need to parse XML in some other way.

`XMLHttpRequest` should already support parsing XML. If this is the only place in the codebase where jQuery is used xhr is potentially a drop in replacement.

Alternatively, the fetch API can be used, but that would require rewriting the rest of this file (and potentially other parts of the codebase!) to deal with promises.

**Comment by JingYenLoh** [comment]
I've hit an issue while replacing jQuery code in the data visualizer. The code itself is straightforward, but the function I'm editing is supposed to enable/disable 2 next/previous buttons in the data visualizer.

The selector used to get the buttons is `'.sa-list-visualizer #previous'` and `'.sa-list-visualizer #next'`. I'm not convinced that these buttons have ever existed in cadet-frontend. Looking at 337577df10d22e21bdccef22f4144a83069c1f11 where they were merged in, I see no reference to these buttons either. I suspect that this function was for whatever codebase it was ported from, and is useless in cadet-frontend.

Can anyone confirm if the visualizer is supposed to have previous and next buttons, @martin-henz ? If it is indeed unnecessary, I will remove it from the library.

**Comment by martin-henz** [comment]
Yes I can confirm that in Source Academy 2 (2017) we recorded every call of `draw_data` (then called `draw_list`). We had a "previous" and "next" button that allowed us to navigate the history of recorded data structures. It was quite useful during lectures to be able to show how data structures evolve during recursion.

For some reason this was abandoned.

I have the feeling that these remnants should be removed. We should take a fresh look at recording for the Data Visualizer and for the Environment Visualizer in CP3108 in Sem 2 AY2020/21, unless someone wants to devote his summer to these features.
