### ISSUE TITLE
Missing annotations in editor gutter

### ISSUE THREAD

**Issue by jiayushe** [source-academy/cadet-frontend#1151]
- `master` branch
![image](https://user-images.githubusercontent.com/42549358/82785339-00dcaf80-9e95-11ea-96b9-154969dd7a8f.png)

- `sa_2021` branch
![image](https://user-images.githubusercontent.com/42549358/82785457-308bb780-9e95-11ea-97a0-0a863cdb0449.png)

**Comment by seanlowjk** [comment]
This is caused by the fact that `(this.AceEdtior.current)` returns `null`. 

As a result, all `annotations` are unable to be retrieved. Will have a look and see what's a possible fix for the `AceEditor`.

**Comment by jiayushe** [comment]
> This is caused by the fact that `(this.AceEdtior.current)` returns `null`.
> 
> As a result, all `annotations` are unable to be retrieved. Will have a look and see what's a possible fix for the `AceEditor`.

`AceEditor` is a react ref and it should not be `null` when editor is rendered in view.

If you try console logging `this.AceEditor.current!.editor.getSession().getAnnotations()`, you will always get an empty array. This suggests that the ace editor itself is unable to parse the editor value properly (using js syntax). I suspect that the changes in sem2 on the editor mode and custom features break this.

**Comment by seanlowjk** [comment]
That's what I suspect too. We'll have a look at it ASAP as this is pretty urgent and needs to fixed before the new semester starts.

**Comment by seanlowjk** [comment]
Annotations have been removed from the Source Academy. 

As a result, this issue can be closed. Thanks for the feedback though.
