### ISSUE TITLE
Grading overviews page crashes or loads with warnings

### ISSUE THREAD

**Issue by Aulud** [source-academy/cadet-frontend#1156]
## [Bug] Grading overviews page crashes or loads with warnings
Seems to be introduced by changes to support React Hooks in PR #1137.

### Bug description
When the SA front-end is run with mocks (i.e. with `USE_BACKEND=FALSE`), loading the grading overviews page (`/academy/grading`) results in the page freezing and crashing shortly after with the following error message.

![image](https://user-images.githubusercontent.com/44989315/82827805-53908880-9ee2-11ea-87f1-464f9584715e.png)

When the SA front-end is ran pointed to a backend instance, loading the grading overviews page instead results in the following console warning.

![image](https://user-images.githubusercontent.com/44989315/82827983-b8e47980-9ee2-11ea-967f-ed1629db9330.png)

Attempting to then fetch grading overviews results in additional console error messages similar to those seen with the frontend using mocks. The offending component seems to be the notification badges that are optionally rendered alongside each submission in the datagrid.

Last updated 25 May 2020, 11:45PM

**Comment by angelsl** [comment]
This is fixed.
