### ISSUE TITLE
Game component crashes on login in development mode

### ISSUE THREAD

**Issue by Aulud** [source-academy/cadet-frontend#1158]
## [Bug] Game component crashes on login in development mode
Related to #666 and #757.

### Bug description
The game component crashes during the initial login to the development SA front-end pointed to a backend instance, i.e. `USE_BACKEND=TRUE` in `.env`. On successful login, the login page `/login` brings the user to `/academy` which then redirects to `/academy/game` as per the configured `Router`.

![image](https://user-images.githubusercontent.com/44989315/82834501-dff77700-9ef3-11ea-9f54-aee53d5f80db.png)

The issue appears to stem from the function `loadingScreen` in the script `story-player-xml.js` being invoked incorrectly to manipulate the DOM. The first invocation passes `null` for both parameters `div` and `canvas` (see red box above), causing an error when attempting to invoke the [`append`](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append) method of DOM nodes.

This error also manifests when manually navigating to the route `/academy` - hence this page is highly suspect as the origin of the error.

Relevant snippets of code:
https://github.com/source-academy/cadet-frontend/blob/33c7704a279910fb26f01586776480f345fde65e/src/components/academy/game/index.tsx#L44-L51

https://github.com/source-academy/cadet-frontend/blob/33c7704a279910fb26f01586776480f345fde65e/src/components/academy/game/story-xml-player.js#L60-L68

### Replication instructions
There are two ways to reliably trigger this bug:
1. Configure the SA front-end to use a back-end, by setting `USE_BACKEND` to `TRUE` in `.env`, then set up the back-end
2. **Method 1a**: Attempt to login to the development front-end - this should raise the error
3. **Method 1b**: Log out and log back in - this should raise the same error
4. **Method 2**: Navigate to `localhost:8075/academy` using the address bar - this should also raise the same error

Last updated 26 May 2020, 2:15AM

**Comment by angelsl** [comment]
This is obsolete since the old game has been removed.
