### ISSUE TITLE
Ace editor has issues loading workers

### ISSUE THREAD

**Issue by blackening** [source-academy/cadet-frontend#1210]
Issue seems to be from https://github.com/source-academy/js-slang/blob/2af3d6c328fc2d70b07da9664a5a3e157addd6a7/src/editors/ace/modes/source.ts#L799

![image](https://user-images.githubusercontent.com/1753927/83959981-fe774e00-a8b5-11ea-888b-5aec9a8aa876.png)

**Comment by angelsl** [comment]
Was fixed a while ago.
