### ISSUE TITLE
Bad setState warning on login and navigation in Academy

### ISSUE THREAD

**Issue by Aulud** [source-academy/cadet-frontend#1232]
## [Bug] Bad setState warning on login and navigation in Academy
Routing-related bug.

### Bug description
The Academy raises the following warning during login or sporadically when navigating between pages in the Academy.

![image](https://user-images.githubusercontent.com/44989315/84408493-c7e75d80-ac3e-11ea-89aa-293bad843897.png)

### Replication instructions
1. Login into the Academy
2. Alternatively, navigate to the Playground, then refresh the page and navigate back to the Academy

Last updated 11 Jun 2020, 11:45PM

**Comment by chownces** [comment]
I cant seem to replicate this at the moment. Has this issue been addressed?

**Comment by chownces** [comment]
Closing as it seems to have been addressed.
