### ISSUE TITLE
Source Academy not starting on Edge

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#1283]
(should we support Edge?)

<img width="1129" alt="Screenshot 2020-06-21 at 3 32 50 PM" src="https://user-images.githubusercontent.com/30220768/85219221-93a93500-b3d4-11ea-8474-dcce8b0121c6.png">

**Comment by anthony-halim** [comment]
The new Microsoft Edge is now using the same engine as Google Chrome; so supporting Chrome should translate to supporting Edge as well. Currently have not encountered any bug specific to Edge; closing this issue until otherwise.
