### ISSUE TITLE
Fix tests not working with redux-persist

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet-frontend#129]
See PR #127.

> There is an issue with redux-persist in the memory it uses (WebStorage). It works when running, but it is not available during tests, that are not on the web. I'll have to use a different type of storage for this.

**Comment by remo5000** [comment]
I looked into this. The part of the code that throws the error checks for the propery `selfStorage` in the `Window`. Normally, the `selfStorage`'s value is `localStorage`, which cannot be created in a test environment as it is defaulted to a `WebStorage`. I'm thinking of overriding this by setting the property in the window as some sort of memory storage.
