### ISSUE TITLE
Use const, let, instead of var in game

### ISSUE THREAD

**Issue by ning-y** [source-academy/cadet-frontend#133]
Low priority

**Comment by ningyuansg** [comment]
Note to those from the future: obviously don't do this manually. There are migration tools out there that transform var declarations to const and let, with good awareness of variable scoping. Use those.

**Comment by geshuming** [comment]
It seems to be already done, unless I'm misunderstanding

**Comment by ningyuansg** [comment]
I was referring to everything in this [src/components/academy/game](https://github.com/source-academy/cadet-frontend/tree/master/src/components/academy/game
).

**Comment by ning-y** [comment]
@jetkan-yk What's up
