### ISSUE TITLE
Stepper: parentheses around operator combinations needed

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#1343]
Examples: 
<img width="641" alt="Screenshot 2020-07-03 at 6 18 00 PM" src="https://user-images.githubusercontent.com/30220768/86459616-a2d79d80-bd59-11ea-9fc1-a096f6b29797.png">

<img width="641" alt="Screenshot 2020-07-03 at 6 15 43 PM" src="https://user-images.githubusercontent.com/30220768/86459519-77ed4980-bd59-11ea-99e9-7c7d4fd4415e.png">

Sometimes the parentheses appear:

<img width="641" alt="Screenshot 2020-07-03 at 6 16 38 PM" src="https://user-images.githubusercontent.com/30220768/86459648-b125b980-bd59-11ea-9544-e9ad9e4b9766.png">

To keep it simple, I think we should consistently place parentheses around any infix operator combinations (including conditional expressions) that appear inside of other infix combinators (excluding conditional expressions).

**Comment by SwampertX** [comment]
In the first screenshot, is `3 * (2 * 1)` the desired outcome?

**Comment by martin-henz** [comment]
> In the first screenshot, is `3 * (2 * 1)` the desired outcome?

Yes, for sure. I don't think the highlighting is enough to show the order of operator application. We need to follow the syntax of the language.

**Comment by zhaojj2209** [comment]
I'll be working on it!

**Comment by zhaojj2209** [comment]
The PR for the fix has been created over on js-slang [here](https://github.com/source-academy/js-slang/pull/656)!

**Comment by martin-henz** [comment]
Fixed in next js-slang version bump.

**Comment by martin-henz** [comment]
checked and working
