### ISSUE TITLE
REPL: repeats previous input, but does not actually enter it

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#1349]
The previous input 
1 + 2;
immediately re-appears in the next REPL input line, but is not captured. Demo of bug:

https://www.youtube.com/watch?v=39zrsGs1LWs&feature=youtu.be

**Comment by Aulud** [comment]
This appears to be a new bug as of the very latest commit c1510789ace05e79865210220caaa423eed296b4; it does not seem to occur with the previous commit 703510654c6594339b136091d2dddecce2f35638 which upgraded a bunch of dependencies.

**Comment by martin-henz** [comment]
This should have been auto-closed by
https://github.com/source-academy/cadet-frontend/pull/1355

(I think it's the "issue" between "fixes" and the number that kept autoclosing from being triggered.)
