### ISSUE TITLE
Achievement: Replace hardcoded NUS Academic Calendar

### ISSUE THREAD

**Issue by jetkan-yk** [source-academy/cadet-frontend#1368]
Refer to https://github.com/source-academy/cadet-frontend/pull/1363#discussion_r456738136

Requires attention after AY20/21 Sem 1

**Comment by martin-henz** [comment]
Indeed. @angelsl : please record this hard-wiring of the semester calendar in the deployment manual.

@jetkan-yk can we avoid such a thing? What is the reason for doing this?

**Comment by jetkan-yk** [comment]
It is just a naive solution of replicating the information from the [NUS Academic Calendar PDF](http://www.nus.edu.sg/registrar/info/calendar/AY2020-2021.pdf).

https://github.com/source-academy/cadet-frontend/blob/58ae103d1947e8308b86d6048620075b6b2322f8/src/pages/achievement/dashboard/subcomponents/utils/DateHelper.ts#L2-L21

To automate the process for the future, perhaps we can: 
(1) call APIs from LumiNUS or NUSMods, or
(2) write a script to extract data from the official academic calendar pdf, or
(3) hard-wire the next 2 AY Calendars (already released by [NUS Registrar's Office](http://www.nus.edu.sg/registrar/calendar): [AY20/21](http://nus.edu.sg/registrar/docs/info/calendar/ay2020-2021.pdf), [AY21/22](http://nus.edu.sg/registrar/docs/info/calendar/ay2021-2022.pdf)) which is a 5 mins effort.

**Comment by jetkan-yk** [comment]
Removed Achievement Week in commit https://github.com/source-academy/cadet-frontend/commit/b569f92ca32b460fc23b03fea656c99bfe243491
