### ISSUE TITLE
Playground REPL with Source 1 WASM repeats past error messages

### ISSUE THREAD

**Issue by Aulud** [source-academy/cadet-frontend#1392]
## [Bug] Playground REPL with Source 1 WASM repeats past error messages
Interpreter or REPL-related bug.

### Bug description
Evaluating a program in the REPL with the Source sublanguage set to Source 1 WebAssembly returns an output that repeats all previous errors in the REPL **if at least one exists**, even if the program is syntactically and semantically sound. Additionally, it appends any new errors to all past REPL outputs (see below).

We begin by evaluating an invalid program (a valid program here does not manifest any bug in subsequent steps). The REPL now contains this, which is correct:

![image](https://user-images.githubusercontent.com/44989315/88564033-4d936100-d065-11ea-9743-99c49b8b50a1.png)

Evaluating another invalid program returns an output that includes the previous error (line 1 of the first program) with the current error (line 2 of the second program). It also appends the current error to the output of the previous program. Both of these are likely unintended - this is the REPL now:

![image](https://user-images.githubusercontent.com/44989315/88564308-a3680900-d065-11ea-9b30-14f51ef44c4e.png)

If we continue by evaluating a valid program (`true;`), the expected output (`true`) is not produced, but instead the combined error is output as the result of this third program - this is the REPL now:

![image](https://user-images.githubusercontent.com/44989315/88564817-47ea4b00-d066-11ea-9280-6017d6dd56ea.png)

If we continue again by evaluating now an invalid program (this time with an undeclared variable `z`), we notice the output (red error message) does not contain the _undeclared variable error_; instead, the error is reported through the hint message instead - this is the REPL now:

![image](https://user-images.githubusercontent.com/44989315/88565405-20e04900-d067-11ea-9cfe-6120735351d3.png)

For comparison, this is the standalone output from evaluating that same invalid program in the REPL, which does correctly report the _undeclared variable error_:

![image](https://user-images.githubusercontent.com/44989315/88565710-90eecf00-d067-11ea-9fb8-dd52a508ea2c.png)

More oddly, if we continue by evaluating an empty program, the REPL repeats the combined errors as the output, even though there should really be none - this is the REPL now:

![image](https://user-images.githubusercontent.com/44989315/88565946-e034ff80-d067-11ea-9621-d54e8d396a88.png)

This bug **does not occur with any other Source sublanguage**, so it may be isolated to the implementation of Source 1 WASM.

### Replication instructions
1. Proceed to the Playground either in your local development front-end or [here](https://source-academy.github.io/playground)
2. Set the Playground's sublanguage to _Source 1 WebAssembly_
3. Evaluate in the REPL a sequence of both valid and invalid Source 1 programs into the REPL, beginning with an invalid program
    - With an invalid program, the REPL should append the new error to all previous outputs from invalid programs
    - With a valid program, the REPL will fail to output the intended value, instead returning an output with all previous error messages

Last updated 27 Jul 2020, 11:45PM

**Comment by btzy** [comment]
The REPL is not supported in Source 1 Wasm, and I'm surprised it even attempted to compile the code from the REPL.  (Wasm does not have plugins / hot loading, so it is somewhat challenging to get this to work.)

So this is a frontend issue, and the fix is to disable the REPL UI from the frontend for Source 1 Wasm.  There was some talk about disabling the REPL in May, but it seems like we never got around to doing it.

I think Wasm is the only variant that does not support REPL, so there wasn't already a flag that we could use.  Is there anyone familiar enough with this part of the frontend, and willing to disable the REPL here?

**Comment by Aulud** [comment]
@btzy Currently, the REPL is already disabled for Source 3 Concurrent, so we can do the same for Source 1 Wasm. Thanks for the explanation (it's interesting that it succeeds in compiling the REPL code when the program is valid).

**Comment by martin-henz** [comment]
It might succeed in compiling the REPL code, but the REPL code cannot refer to names declared in previously evaluated programs. This renders the REPL useless at best, and misleading at worst.
