### ISSUE TITLE
Game music persists upon navigating away from Game

### ISSUE THREAD

**Issue by Aulud** [source-academy/cadet-frontend#1411]
## [Bug] Game music persists upon navigating away from Game
Feature bug.

### Bug description
The background music from the Game (accessed at `/academy/game`) persists even if the user navigates away to another page (e.g. Missions, Playground).

Upon navigating back to the Game, a new backing track plays over the existing track, and neither are stopped when navigating away from the page. This results in a consistent increase in total memory use each time the Game page is accessed.

### Replication instructions
1. Login to the Source Academy in the development environment; you will be brought to the Game on successful login
2. Navigate to some other page in the Academy, e.g. the Playground or Grading - the background Game music should remain

Last updated 2 Aug 2020, 11:45PM

**Comment by anthony-halim** [comment]
This is already fixed recently, now we stop all background music when the game React component is unmounted. Additionally, we also always check that user are still at /academy/game URL before playing any background music.

Can you confirm that this bug still persist?
