### ISSUE TITLE
SOUNDS library on Safari: recording not working

### ISSUE THREAD

**Issue by samuelfangjw** [source-academy/cadet-frontend#1414]
Error when recording sounds using record_for, ReferenceError: Can't find variable: MediaRecorder. Once MediaRecorder is enabled under Develop -> Experimental Features -> MediaRecorder, this error goes away. (Perhaps some way of letting safari users know that the feature must be enabled?)

However, even after enabling the MediaRecorder, I am still unable to playback sounds that have been recorded. I still get the error "Error: recording still being processed" even though the recording is finished (after second beep is played).

![2020-08-02 13 49 12](https://user-images.githubusercontent.com/60355570/89116467-f65b1980-d4c6-11ea-9d91-e18c54fd83dc.jpg)

**Comment by angelsl** [comment]
Closing this because we don't support Safari.
