### ISSUE TITLE
Console log dispatch from display() does not cause re-render

### ISSUE THREAD

**Issue by remo5000** [source-academy/cadet-frontend#142]
### Cause
- The `EVAL_EDITOR` action called from within the Playground runs and maps to a new state
- However, it does not trigger a re-render of the Playground
- All actions with type `HANDLE_CONSOLE_LOG` map the state to a new (shallow equality returns false) state, but do not trigger re-render as well.

### Exception
- When calling `EVAL_EDITOR` from the browser (the same way as `display()`), all the re-renders trigger as expected.

Really weird bug, and I can't seem to debug Redux itself. I might consider opening an issue on their end, as calling the dispatch function from other parts is something that has been [recommended](https://github.com/reduxjs/redux/issues/1714) before. Additionally, I've written a short post on it [here](https://medium.com/@vigneshshankar_72792/redux-external-action-dispatch-and-the-plight-of-re-rendering-3f1a699ff418).

**Comment by ningyuansg** [comment]
## Notes:

- Bug is encountered in both the playground as well as assessment workspaces
- Bug is encountered for both the run as well as the eval buttons
  - i.e. both `handleEditorEval` and `handleReplEval`
  - i.e. both `evalEditor` and `evalRepl`
- Playground is from connected component from default export of containers/PlaygroundContainer
  - Connected component Playground is from component Playground from components/Playground
    - Component Playground is from component Workspace in components/workspace/index
- Assessment's workspace is from workspace component from components/workspace/index
  - Props passed to workspace component are connected props of assessment from containers/assessment/index
- Dispatches in the two different containers are differentiated by creating a closure with variable `location` in each container, corresponding to the strings `'playground' | 'workspace'`
