### ISSUE TITLE
Collab Editing Broken after Frontend Refactoring

### ISSUE THREAD

**Issue by jiayushe** [source-academy/cadet-frontend#1430]
- Frontend crashed when creating sessions
![image](https://user-images.githubusercontent.com/42549358/89274872-1845cf00-d674-11ea-9c67-218a10ecab37.png)
- This only happens after the frontend refactoring commits

**Comment by anthony-halim** [comment]
The collab editing is still working until #1377, and broke after #1219. Tagging @blackening into this issue as well.

**Comment by JinHao-L** [comment]
No Session id created when "invite" is pressed (Tested on chrome)
![image](https://user-images.githubusercontent.com/52820430/89901837-44cf8d00-dc18-11ea-8f48-9b80c0d9157e.png)
![image](https://user-images.githubusercontent.com/52820430/89901899-587af380-dc18-11ea-9a22-f39fca4afe5e.png)

**Comment by angelsl** [comment]
@JinHao-L Where are you testing this? It has only been deployed to GitHub Pages; the CS1101S deployment doesn't have it yet.

**Comment by JinHao-L** [comment]
Hi @angelsl, it appears that the problem was on my end. It works once I cleared the cookies. The feature is working well on both GitHub Pages and the CS1101S deployment! 👍 

Thanks for the prompt reply and sorry for any inconvenience caused!

**Comment by angelsl** [comment]
@JinHao-L Yup, I just deployed the latter. No worries!
