### ISSUE TITLE
Achievement: Use moment.js for DateHelper

### ISSUE THREAD

**Issue by jetkan-yk** [source-academy/cadet-frontend#1439]
### Refactor Achievement Date Helper
https://github.com/source-academy/cadet-frontend/blob/c3be01c77969650c10915babcfc2ee77ed26aa16/src/commons/achievement/utils/DateHelper.ts#L1-L64

#### Use [moment.js](https://momentjs.com/docs/) to prettify dates and deadlines, since it is used by the common Date Helper
https://github.com/source-academy/cadet-frontend/blob/c3be01c77969650c10915babcfc2ee77ed26aa16/src/commons/utils/DateHelper.ts#L1-L43

**Comment by jonas-chow** [comment]
Working on this
