### ISSUE TITLE
Logging in resets playground editor value to default

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet-frontend#145]
The text in the editor of the playground does not persist after a log in. Instead, the text in the editor reverts to its default value.

**Expected bahaviour**: The text in the editor of the playground is the same before and after logging in

**Steps to replicate**:

1. Navigate to the playground
2. Edit the text in the editor
3. Navigate to the academy (mounts the log-in component)
4. Log-in via IVLE (redirects to academy)
5. Navigate to the playground
6. The text in (2) has now disappeared, and the editor is instead showing the default text.

**Comment by remo5000** [comment]
It is expected by design, because we do not cache the editor value. I agree that it should persist like this though. It will also make the Playground more persistent. A limit to the text size must be implemented, as localStorage is only so big.
