### ISSUE TITLE
is_rune check fails sometimes

### ISSUE THREAD

**Issue by openorclose** [source-academy/cadet-frontend#1473]
![image](https://user-images.githubusercontent.com/66359353/90502872-240bb800-e181-11ea-9d38-dd195bcae861.png)

Steps to reproduce:

1. Change to runes library
2. type `show(heart);` in the repl
3. press eval

If you press run first on the left side and then press eval, the rune is displayed as expected.

**Comment by martin-henz** [comment]
this is fixed in the meantime
