### ISSUE TITLE
Keyword let purple in Source §3

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#1528]
<img width="433" alt="Screenshot 2020-10-08 at 1 40 17 PM" src="https://user-images.githubusercontent.com/30220768/95419484-501b0c80-096c-11eb-892c-e294dab4f11d.png">

Should be yellow, as a legit keyword in Source §3.

**Comment by BobbyZhouZijian** [comment]
fixed in https://github.com/source-academy/js-slang/pull/788. I think we can close this.
