### ISSUE TITLE
Missing red dots for auto-submitted missions

### ISSUE THREAD

**Issue by zhaohuanqdcn** [source-academy/cadet-frontend#1556]
If a mission / quest is left empty by the student and is automatically submitted after the deadline (i.e. no attempt), the work submitted is not graded as 0 mark (still needs to save every question as 0 mark manually) and no red dot is shown (possibly forget to grade).

**Comment by angelsl** [comment]
Duplicate of https://github.com/source-academy/cadet/issues/495
