### ISSUE TITLE
NaN, Infinity

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#16]
these two variables should be defined and assigned to the right values

**Comment by ningyuansg** [comment]
Hi Prof Henz, is there an up-to-date specification that we can follow for §1? I realise that we've been following [this document](http://www.comp.nus.edu.sg/~henz/sicp_js/source_1.pdf) dated April 17, which excludes these symbols `NaN` and `Infinity`.

We'll get these fixed by sprint 1, though!

**Comment by martin-henz** [comment]
Oh, sorry. Yes. 
[source_1.pdf](https://github.com/source-academy/cadet-frontend/files/2016847/source_1.pdf)

**Comment by martin-henz** [comment]
Will upload this to sicp_js

**Comment by martin-henz** [comment]
Now also in sicp_js
