### ISSUE TITLE
Sourcecast Table UI bug after #1582 ag-grid-react dependency update

### ISSUE THREAD

**Issue by chownces** [source-academy/cadet-frontend#1634]
#1582 

Currently:
![image](https://user-images.githubusercontent.com/53928333/108615004-a6c84500-743a-11eb-85dc-d4e7fdf4dbab.png)

Expected:
![image](https://user-images.githubusercontent.com/53928333/108615164-4a662500-743c-11eb-9a36-d002e9e9eac2.png)

**Comment by YaleChen299** [comment]
This issue should be fixed by the above pr.
