### ISSUE TITLE
Typing in Source §1

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#17]
Currently, violations of Source §1 typing are not leading to error messages. Examples:

```javascript
> "a" < 1;
false
> true && 1; // this one is particularly tricky
1 
> - false;
0
> - true;
-1
> !0;
true
> -"asdf";
NaN
> 1 * "asdf";
NaN
```

**Comment by ningyuansg** [comment]
According to the specifications, the strict equality operator `===` only accepts two arguments of the same type, i.e. `'1' === 1` would be illegal.

Can I check if this is the intended specification? The [EMACScript specification](https://www.ecma-international.org/ecma-262/8.0/index.html#sec-strict-equality-comparison) accepts the use of strict equality between different types, and I think that's reasonable.

**Comment by martin-henz** [comment]
Yes, '1' === 1 should be illegal and produce a runtime error. I think it's economical and mentally hygienic to stick to a strict runtime type discipline. My feeling is that the "reasonable" use cases would be rare. I think it's a good thing for the students to see that data types are important, despite the fact that we generate errors only at runtime. The case for a strict "===" is weaker than the case for a strict "<"; I don't want to explain
> "1" < 1;
false
> 1 < "1";
false
I think it's a bit simpler to just require equal types for all comparison operators.

**Comment by ningyuansg** [comment]
Understood, we'll implement that then. Thank you!
