### ISSUE TITLE
Documentation on features and course workflow within Source Academy

### ISSUE THREAD

**Issue by chownces** [source-academy/cadet-frontend#1727]
As we shift to become multi-tenant, documentation should be added to make onboarding for new module instructors easier. Features and the general workflow for students and staff can be added for:
- Using the cadet backend
- Using GitHub Classrooms

**Comment by martin-henz** [comment]
A preliminary structure for this is here:
https://github.com/source-academy/general

Let's use the issue: https://github.com/source-academy/general/issues/2
to discuss the structure.
