### ISSUE TITLE
Playground: spurious popup "please log in again"

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#1752]
<img width="1029" alt="Screenshot 2021-05-27 at 1 14 07 PM" src="https://user-images.githubusercontent.com/30220768/119769749-9b7b2e80-beed-11eb-9de3-d1adbe6bcf12.png">

Reproduce in Chrome:
* refresh 
* enter a program
* press "Run"

**Comment by chownces** [comment]
Just had a look. This was introduced in the recent achievements PR. Every trigger of the `EVAL_EDITOR` reducer logs an achievement event, after which `processEvents` is triggered and a request is sent to the backend. However the user is not logged in, and this causes an error in the request. This is also causing issues in the Github Assessments PR now.

Should be able to disable this with a conditional in `processEvents`
