### ISSUE TITLE
Change hasChapterSelect to canChapterSelect

### ISSUE THREAD

**Issue by remo5000** [source-academy/cadet-frontend#179]
Rationale is that during an assessment, the student can be aware of what version of slang they are using.

**Comment by seanlowjk** [comment]
If I am not mistaken, does this issue have overlap with #953 or are they two separate issues by themselves? Cause from my understanding, it seems that we want the `Source Chapter` to be shown to students with respect to their assessments.

**Comment by martin-henz** [comment]
What is the difference between ``hasChapterSelect`` and ``canChapterSelect``?

**Comment by Aulud** [comment]
Closing this issue since `canChapterSelect` no longer exists in the codebase, and PR #1199 appears to address the purpose of this issue.
