### ISSUE TITLE
Interactive SICP: clicking on footnote goes into inconsistent state

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#1809]
Example: https://source-academy.github.io/interactive-sicp/2

Clicking on footnote 1 after "know their detailed structure.1" leads to this:

<img width="1051" alt="Screenshot 2021-06-18 at 5 46 16 PM" src="https://user-images.githubusercontent.com/30220768/122542924-d2acad80-d05d-11eb-9486-2b806924edfe.png">

There is no way to scroll up such that the full browser height is used for the text. Instead, the bottom 2/3 remains occupied by the image. The learner can only go back to a consistent state by refreshing the browser or by clicking the browser back button.

**Comment by samuelfangjw** [comment]
Noticed this last night too, seems to work on Firefox but not other browsers.  Another issue is that links to sections of text don't seem to work properly, so going straight to https://source-academy.github.io/interactive-sicp/2#p2 should jump to paragraph 2 of the page but it doesn't seem to work at the moment.
