### ISSUE TITLE
Parallel execution of programs not blocked

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet-frontend#193]
We relied on the hiding of eval and run buttons to create a soft block against student executing source programs while a source program is already running. 

However, we need to be stricter about this restriction, since the <shift-enter> evaluation is not disabled.

<div align="center">
    <img src="https://thumbs.gfycat.com/OffbeatElatedHarrier-size_restricted.gif">
</div>

In the above program, `display` has only 4 calls to it.

**Comment by remo5000** [comment]
Yep, perhaps a check in `context.runtime.isRunning` would suffice

**Comment by ningyuansg** [comment]
#197 restarts the execution of the program, if an evaluation action is sent to the saga and there is already a program running.

This other method, checking isRunning, does nothing if an evaluation action is sent to the saga and there is already a program running. Admittedly, it's a more elegant solution, but to the end user, it would make the IDE feel irresponsive.
