### ISSUE TITLE
REPL value missing when at the bottom of screen and typing

### ISSUE THREAD

**Issue by remo5000** [source-academy/cadet-frontend#195]
#### Steps to reproduce
- Scroll slider till REPL input is at the bottom of screen
- Type, and it **should not show up**
- Focus on something else, and it **should show up**, but disappear when focusing on it again.

Discovered in, but not due to 7a2c087  

Similar to #168

**Comment by remo5000** [comment]
Turns out it only happens to Macs when running in development. Production is fine, and other OSes (tested on Debian) do not experience this in development

**Comment by martin-henz** [comment]
I've seen this quite a few times on Mac. A bit annoying. I usually clear the REPL history to get rid of the problem until the REPL fills the tab again.

**Comment by martin-henz** [comment]
Seems fine now.
