### ISSUE TITLE
"Betcha" button for missions/quests/paths

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#202]
The idea is to let students "bet" that their assessment solution is correct. Their solution would be irrevocably frozen, similar to an expiry of the assessment deadline. The students would be credited with XP, corresponding to the number of hours between pressing the button and the deadline.

**Comment by ningyuansg** [comment]
Hi Prof. Again, this implementation relies more on the backend, so I'll move it to the backend repository. The current schema for assessments in the database cannot easily support this feature.

**Comment by ningyuansg** [comment]
Moved to https://github.com/source-academy/cadet/issues/127.
