### ISSUE TITLE
Implement code-splitting

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet-frontend#211]
For better loading on client-side, and also because, ridiculously enough, a standard build server running `t2.micro` does not have enough memory to build our application, even if a limit of 1gib is imposed on the node runtime:

```
[BUILD] bitnami@ip-172-13-52-105:~/cadet-frontend$ node --max_old_space_size=1024
...
The build failed because the process exited too early.
This probably means the system ran out of memory or someone called `kill -9` on the process
```

**Comment by geshuming** [comment]
Doesn't seem to be an issue currently?
