### ISSUE TITLE
Save the api-fetched tokens into browser cookie

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet-frontend#216]
@remo5000 iirc you mentioned this is why it prompts for login every refresh

**Comment by remo5000** [comment]
Found the cause. `role` was not stored, causing a redirect to login  at the function `redirectToAcademy()`. `localStorage` was working as expected

**Comment by ningyuansg** [comment]
Right, my bad actually I didn't change how the stuff was being saved when I added the check that role should not be undefined for user to access academy.
