### ISSUE TITLE
URL for playground in textbook

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#226]
Currently, textbook Chapter 1 uses URLs of the following kind:
http://stg-cadet-frontend.s3-website-ap-southeast-1.amazonaws.com/playground#filename=&library=Source%20%C2%A71&lz=FAFgHAbA3MxA&read_only=false
where %C2%A7 stands for the section sign §. However, the IDE loads Source §2.

**Comment by ningyuansg** [comment]
Hi prof, I had previously opened this up as an issue at https://github.com/source-academy/sicp/issues/5. We represent the source chapter as a single integer 1 or 2 instead of a url encoded string (`Source%20%C2%A71`) since the former is more space efficient and readable.

**Comment by ningyuansg** [comment]
Would prefer that this change be implemented on [source-academy/sicp](https://github.com/source-academy/sicp) instead of here, if that's okay

**Comment by martin-henz** [comment]
Yes, sure. Didn't see the new format. Will tell Piao Piao about it. Thanks.

**Comment by ningyuansg** [comment]
No problem, closing in favour of https://github.com/source-academy/sicp/issues/5.
