### ISSUE TITLE
Abstract AssessmentWorkspace & GradingWorkspace

### ISSUE THREAD

**Issue by ning-y** [source-academy/cadet-frontend#229]
They're basically the same thing at this point

**Comment by remo5000** [comment]
Grading needs to use the GradingEditor (in a side content), does not need to save mcq and editor value answers. I'm thinking of using inheritance to tackle this issue, what do you think?

**Comment by ningyuansg** [comment]
Sure, sounds like a good use case for that.

**Comment by yyc** [comment]
I'll take a look at this to learn more about it

**Comment by angelsl** [comment]
Closing in favour of #1555 (duplicate).
