### ISSUE TITLE
Access to Paths 

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#243]
The Paths do not come with stories of their own. Instead, they should be accessible from the Academy CLASSROOM, by clicking the TRAINING room.

**Comment by ningyuansg** [comment]
Yep, this behaviour is already implemented on our end.

**Comment by remo5000** [comment]
@ningyuansg I think the issue might be how the button says "Skip story and attempt" when there is no story. We can check the assessment type for this.
