### ISSUE TITLE
Ternary expressions should only accept boolean first arguments

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet-frontend#26]
Probably part of RTTC.

**Comment by ningyuansg** [comment]
Hi Prof @martin-henz,

Currently, the specifications state that ternary expressions will only accept boolean expressions as their first argument (_"Preceding `?`, Source only allows boolean expressions"_). Should we also implement the same restriction for `if` statements?

Meaning, should the type of `a` in the following program be required evaluate to a boolean value?
```javascript
if (a) {
    0;
} else {
    1;
}
```

**Comment by martin-henz** [comment]
Yes, that was a gap in the specs. It should say:

Preceding ? and following if, Source only allows boolean expressions.

I've pushed the change in the specs.
