### ISSUE TITLE
Help button

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#260]
There should be a help button at a prominent location. For our deployment of the Source Academy, this is the text that should pop up when pressing the button:

The Source Academy is an experimental environment for learning programming in the module CS1101S at the National University of Singapore. Please use the following resources when you encounter issues with this system.

- For critical technical issues that seriously affect your learning experience, email the Technical Services of the NUS School of Computing at techsvc@comp.nus.edu.sg  or call 6516 2736.
- For non-critical technical issues, such as enhancement suggestions, please use the issue system of the Source Academy repositories on github: https://github.com/source-academy
- For issues related to the content of missions, quests, paths and contests, use the respective forum at  https://piazza.com/nus.edu.sg/fall2018/cs1101s, or approach your Avenger, Reflection instructor or lecturer.

**Comment by ningyuansg** [comment]
We can place the help button on the student's 'profile' page. The profile page is opened by a button on the top-anchored navigation bar. Would this be acceptable?

**Comment by martin-henz** [comment]
Not to be paranoid, but if navigation to the students' profile page is part of the problem that the student is trying to report, this will not be so good. Best would be a help button that is always visible. Maybe at the top, next to "News" and "Material"?
