### ISSUE TITLE
Data visualiser should only appear after a call to draw_list

### ISSUE THREAD

**Issue by ning-y** [source-academy/cadet-frontend#283]
In order of preference,

1. The list visualiser appears in the repl output in the same way that a rune does, or
2. The list visualiser tab does not render (including the button to switch to it) until a call to `draw_list`.
    - Calling draw_list also automatically switches the tab to the list visualiser.

**Comment by martin-henz** [comment]
Alternatively: The data visualiser should be always there (from Source §2 onwards), and show a default help text before draw_data is called the first time:

The data visualiser visualises data structures. It is activated by calling the function draw_data(the_data), where the_data is that data structure that you want to visualise.

**Comment by angelsl** [comment]
This seems to no longer be a problem.
