### ISSUE TITLE
Use blueprintjs tabs instead of self-implemented ones

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet-frontend#284]
We (or at least I) missed that blueprintjs already has [a tab component](https://blueprintjs.com/docs/#core/components/tabs.tab). I'm mostly referring to the side-content of the workspace component.

**Comment by remo5000** [comment]
I found that the behaviour of it is a bit iffy, but we can try it out first

**Comment by alcen** [comment]
Planned - this should resolve https://github.com/source-academy/cadet-frontend/issues/291 and increase functionality of the side content

**Comment by alcen** [comment]
Resolved in #740!
