### ISSUE TITLE
Make "Comments" tab the default tab when comments are present 

### ISSUE THREAD

**Issue by remo5000** [source-academy/cadet-frontend#291]
- In an AssessmentWorkspace, the activeTab is still `0` when it gets reset. 
- The easiest way to set the active tab index is to leverage the optional arguments of `handleResetWorkspace`. 
- The main problem is getting the index of the comments tab after the tabs are all rendered. A trivial solution is to simply pass `2` as the tab index (As the tabs are Task, Long summary, and Comments) but a better one would be to get the index of the comments tab when it is being added, and use that when resetting the workspace.

**Comment by Aulud** [comment]
Issue has been satisfactorily resolved as of PR #819.
