### ISSUE TITLE
Feedback upon path completion

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#301]
Students find completion feedback lacking when a path is completed. Here a student comment. I think this is legit, and we should look into it.

**Could an email notification be sent out once the Path is accessible, so we don't have to keep refreshing the page (and given that the due date is tomorrow)? Thanks!

Martin's answer: You should complete path P1 before tomorrow, but note that it is not connected to a CS1101S assessment component. Path P1 is meant as an ungraded self-assessment.

We will look into improving the feedback upon path completion. Thanks for the suggestion.

-martin**

**Comment by ningyuansg** [comment]
Implementation will have to be on the backend. Frontend runs on the client-side and is not suitable for this task.

/move to cadet
