### ISSUE TITLE
Clicking on diamond logo in game leads to 404

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet-frontend#305]
Clicking on the diamond logo on the top left hand corner of the game leads to 404 page.

![image](https://user-images.githubusercontent.com/11135744/44222508-4e53c500-a1b7-11e8-99fb-f11340cee2c5.png)

**Comment by ReignOfComputer** [comment]
Able to reproduce, openWristDevice() leads to 404 as /academy/news does not exist.

Related line: https://github.com/source-academy/cadet-frontend/blob/master/src/components/academy/game/create-initializer.js#L51

**Comment by ningyuansg** [comment]
@ReignOfComputer Thanks! Will you be willing to open a PR for this change?

**Comment by ReignOfComputer** [comment]
Spoke to Prof @martin-henz, will redirect students to IVLE.

**Comment by martin-henz** [comment]
nice!
