### ISSUE TITLE
lk-curveDisplay Image Asset needs cleaning

### ISSUE THREAD

**Issue by ReignOfComputer** [source-academy/cadet-frontend#306]
The display in LK's room, lk-curveDisplay, needs some cleaning up. Sorry, pet peeve.

![image](https://user-images.githubusercontent.com/2667537/44223511-66791380-a1ba-11e8-84bb-bc6f28da0655.png)

**Comment by ReignOfComputer** [comment]
![normal](https://user-images.githubusercontent.com/2667537/44247242-84c02d00-a215-11e8-9317-888cd3f18dd8.png)

There I fixed it.

**Comment by anthony-halim** [comment]
Uploaded the clean version through story simulator, can be checked at objects/lk-curveDisplay/normal.png
