### ISSUE TITLE
Add/hook up the additional endpoints for xp

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet-frontend#316]
Backend endpoints to be added/hooked up after https://github.com/source-academy/cadet/pull/232 is merged: 
- `User`, add `total_xp`
- `Grading`, add `xp`, `xp_bonus`, `xp_adjustment`
- `Assessment`, add `max_xp`, `xp`, `grade`

**Comment by remo5000** [comment]
Thanks for the summary of the properties @indocomsoft . I'll take a swing at this today

**Comment by remo5000** [comment]
Fixed by #334
