### ISSUE TITLE
Editor disappears when Side content is hidden and Editor code is run

### ISSUE THREAD

**Issue by SRSR333** [source-academy/cadet-frontend#317]
As mentioned in the title, the source code editor disappears when: 

1. the REPL and hint-box panels on the right side of the screen are completely minimised,

2. **AND** the code in the editor is run.  

The Source Academy needs to be refreshed to make the editor reappear. It does not matter how the window is resized. 

Specs and software used:

Chrome 68.0.3440.106
Windows 10 Pro v1803

This is best demonstrated with a screen-capture:
![output](https://user-images.githubusercontent.com/3754080/44463010-ee42a000-a648-11e8-9873-b0b355e2b83f.gif)

I tend to expand out the entire editor because I frequently work with two windows on one display, and the hint-box/REPL on the right requires that I wrap my code very often. 

As a suggestion: when code in the editor is run, perhaps the REPL can slide in from the right as an overlay, displaying the output for, say, 5 seconds, and slide back out.

**Comment by remo5000** [comment]
Thank you for creating this issue (with relevant information and the gif as well). We're pretty busy with other issues and improvements right now, but we'll look into this later on.

**Comment by remo5000** [comment]
Note to any developers: The problem occurs when `editorWidth` is 100%, and the side content is rendered (due to an update in the REPL output). The `editorWidth` remains at 100% but in reality is 0% (side content is the whole screen), and can't be changed further (demonstrated in the gif)

**Comment by martin-henz** [comment]
Not reproducible
