### ISSUE TITLE
Task numbering in missions, quests, paths

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#330]
The numbering is currently not obvious. Students only see a number when clicking on the windmill icon. They see a Task #, where the numbering starts with 0.
<img width="632" alt="task numbering" src="https://user-images.githubusercontent.com/30220768/44577613-28847c80-a7c4-11e8-9eee-a1e9889ebecf.png">

I think we should start the numbering with 1 and display the task somewhere more prominently.

**Comment by Aulud** [comment]
Hi Prof, is this issue still relevant currently? The Academy presently does show the question number in the navigation bar for assessments, although this may not always correspond to the intended task number depending on the question description.

![task-numbering](https://user-images.githubusercontent.com/44989315/64272118-40631480-cf71-11e9-9d2a-eac89836665f.png)

It seems the on-hover tooltip for the question description has also been updated to use 1-indexing.

**Comment by seanlowjk** [comment]
With Regards to this issue, I think we should be able to close it for now. 
Given that tasks are now 1-indexed. 

Let's re-open this if we were to spot any bugs with respect to this issue
