### ISSUE TITLE
Grading interface should show name of Avenger

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#347]
Currently any Instructor needs to look up the student in IVLE in order to find the Avenger who has done the grading. (This is for QA of grading.)

**Comment by remo5000** [comment]
@indocomsoft Is this something that can be passed in the request? I can definitely add it in. There's going to be issues though, such as what happens where multiple people grade a submission

**Comment by jiachen247** [comment]
#426 should resolve this issue. Students can now see the name of the avenger who last graded their submission.
