### ISSUE TITLE
Implement question number for assessments

### ISSUE THREAD

**Issue by jiachen247** [source-academy/cadet-frontend#357]
Currently cadets have no idea how many questions each mission/path has while doing them.
It would be nice to have a "2/3" indicator to tracked the numbers of questions completed / left. 

let me know if yall need help with the pr!

**Comment by blackening** [comment]
Do you want to do it? If you do this, this can be added to an e-portfolio. I believe I can create a portfolio quest which grants xp for this, later in the semester.

**Comment by jiachen247** [comment]
sure thing!! let me finish my missions that ill start on this haha can kiv a proper progress bar.

**Comment by jiachen247** [comment]
hahaha no worries!!! as long as it ends up inside HAHA

**Comment by jiachen247** [comment]
#366

**Comment by jiachen247** [comment]
@blackening any updates for xp? hahaha how much xp is everyone having question numbers worth HAHA thakies :-)
