### ISSUE TITLE
draw_list(function) shows code in the list visualiser

### ISSUE THREAD

**Issue by C-likethis123** [source-academy/cadet-frontend#360]
When I coded 'draw_list(function)' (where function is the name of any predeclared function), it returns the code of the function in the List Visualiser. 

<img width="1296" alt="interesting" src="https://user-images.githubusercontent.com/27060502/45137111-d7b84f00-b1d9-11e8-8c5b-229058db9a73.png">

**Comment by martin-henz** [comment]
This bug appears to be fixed.
