### ISSUE TITLE
Override default implementation of toString for Objects in Source

### ISSUE THREAD

**Issue by jiachen247** [source-academy/cadet-frontend#406]
Currently in source academy,
`display({"abc": 1}); // [object Object]`

To view the objects in source academy, we use the _JSON.stringify_ method exposed to us.
`display(stringify({"abc": 1})); // "{"abc":1}"`

I don't know if its intentional but stringify feels really out of place which could give rise to unnecessary confusion.

Can we add to slangHelper to check for object and then return the stringified version? 
or just override Object.prototype.toString and let all objects inherit from that.

**Comment by martin-henz** [comment]
It will be important to check for circularity. Environments are usually circular data structures.

**Comment by martin-henz** [comment]
Duplicate Issue:
https://github.com/source-academy/js-slang/issues/135
