### ISSUE TITLE
Repl does not scroll down automatically on shift-enter

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet-frontend#41]
![](https://thumbs.gfycat.com/SharpAccomplishedAsiandamselfly-size_restricted.gif)

**Comment by remo5000** [comment]
I believe this can be fixed using a `ref` and a call to it in `componentDidUpdate()`, but the REPL component is stateless, so I will change that first.

**Comment by remo5000** [comment]
Blocked by #48
