### ISSUE TITLE
Source chapter selector is hidden when repl is resized

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet-frontend#42]
Probably just put it on the left together with the editor run button.

![](https://thumbs.gfycat.com/FlamboyantArcticGar-size_restricted.gif)

**Comment by remo5000** [comment]
Was thinking about a way to make use of responsiveness to show a "smaller" menu when that part is crunched, and eventually not showing anything at all (as opposed to a sudden disappearance). That, or hiding it like an overlay instead of disappearing.

**Comment by ningyuansg** [comment]
Fixed with 182a005
