### ISSUE TITLE
Parsing .env boolean values

### ISSUE THREAD

**Issue by jiachen247** [source-academy/cadet-frontend#429]
Currently, in .env `REACT_APP_USE_BACKEND=` is left empty to set to false and setting any value here results in using the backend.

This is really counter intuitive, we should pattern match the value here to 1/true/ or 0/false to use or not use the backend respectively.

keep in mind that dotenv parses all valuse as strings
https://github.com/motdotla/dotenv/issues/51

And then update the readme  and template .env

**Comment by LeowWB** [comment]
will look into this

**Comment by jiachen247** [comment]
closed with #430
