### ISSUE TITLE
Regarding auto-run feature

### ISSUE THREAD

**Issue by ccyccyccy** [source-academy/cadet-frontend#467]
#466 added auto-run for Playground only. Should we add this feature for **all** missions in the assessment workspace as well? 

Also, student's autorun setting is preserved after closing the browser. Should it be defaulted to off whenever a workspace is freshly rendered?
https://github.com/source-academy/cadet-frontend/pull/466#issuecomment-468760971

**Comment by martin-henz** [comment]
I think the auto-run feature should be available for missions, and that we should preserve the autorun setting after closing the browser. These two decisions will maximize the exposure we have to the feature so that we can decide which way to go before the semester.

**Comment by martin-henz** [comment]
Answered in https://github.com/source-academy/cadet-frontend/issues/468
