### ISSUE TITLE
Why is there an export here?

### ISSUE THREAD

**Issue by blackening** [source-academy/cadet-frontend#487]
https://github.com/source-academy/cadet-frontend/blob/c93fb65f26159d702e012632347cfc01f752b777/public/externalLibs/list.js#L352

**Comment by martin-henz** [comment]
No idea.

**Comment by martin-henz** [comment]
This is probably not needed.

**Comment by martin-henz** [comment]
Fixed by: https://github.com/source-academy/cadet-frontend/pull/621
