### ISSUE TITLE
mission-editing UI review.

### ISSUE THREAD

**Issue by blackening** [source-academy/cadet-frontend#491]
1. Should be able to edit **both** template and solutions.
2. Why have duplicate tab?
![image](https://user-images.githubusercontent.com/1753927/54868691-3b971380-4dca-11e9-84f5-74572ce213e2.png)

3. Global settings should look global. Move the following into "global":
![image](https://user-images.githubusercontent.com/1753927/54868705-5e292c80-4dca-11e9-875e-a22a504a52a9.png)
Adding new questions

![image](https://user-images.githubusercontent.com/1753927/54868710-6da87580-4dca-11e9-95ef-3785cb0adc3f.png)
Mission briefing

![image](https://user-images.githubusercontent.com/1753927/54868718-89ac1700-4dca-11e9-92d1-66c1c2d129c4.png)
 
Global deployment

4. Should be able to rearrange questions.

**Comment by martin-henz** [comment]
Ger Hean says it's fixed.
