### ISSUE TITLE
Mission-editing: Mission xp/grade doesn't update when questions change.

### ISSUE THREAD

**Issue by blackening** [source-academy/cadet-frontend#492]
![image](https://user-images.githubusercontent.com/1753927/54868858-0db2ce80-4dcc-11e9-8456-11f12924dcca.png)
![image](https://user-images.githubusercontent.com/1753927/54868877-4c488900-4dcc-11e9-8e7c-e67eb5234d7f.png)

**Comment by gerhean** [comment]
Fixed
