### ISSUE TITLE
Mission-editing: placeholders

### ISSUE THREAD

**Issue by blackening** [source-academy/cadet-frontend#493]
![image](https://user-images.githubusercontent.com/1753927/54868886-61251c80-4dcc-11e9-8705-c8b8ffe09c31.png)

Labels are unclickable if cleared. Add a placeholder.

**Comment by gerhean** [comment]
Placeholder for empty string added.
Working on placeholder for spaces and newlines.
Please inform me of other characters which may also cause problems

**Comment by gerhean** [comment]
fixed for empty string, spaces and newline
