### ISSUE TITLE
Tool tips for Source Academy buttons currently contain default texts

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#529]
The icons in Source Academy all have a default mouse-over tooltip, which is not connected to the purpose of the respective functionality. For example, the tooltip for the diamond symbol on the left of "Source Academy" says: "symbol-diamond". 

If the button has a tooltip under the button name, the default tooltip of the icon currently pops up as well, for example:

<img width="244" alt="Screenshot 2019-04-15 at 9 59 33 AM" src="https://user-images.githubusercontent.com/30220768/56103428-5aba3880-5f65-11e9-9322-b19fc0074dfc.png">

The tooltips should be handled in a uniform, consistent manner, across the frontend.

**Comment by alcen** [comment]
Known bug in blueprintjs v2.x.x, fixed in https://github.com/source-academy/cadet-frontend/pull/685
