### ISSUE TITLE
About: Developers: many names missing

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#546]
Proposal: all developers who contributed more than 100 lines should be listed.

src/components/dropdown/About.tsx

**Comment by martin-henz** [comment]
Ning Yuan suggests that we use the github API to extract contributors:
It'd be nice to implement the list automatically. Use the github api (e.g. use https://www.npmjs.com/package/github-api) to pull a list of contributors once during every build, maybe?

**Comment by martin-henz** [comment]
I think it was @Rrtheonlyone who showed me how to use the github API in order to give credit to the developers in an About page. I think something like that could boost our developers' motivation. Which of our teams could look into this?

**Comment by geshuming** [comment]
To be resolved in #609
