### ISSUE TITLE
ENV: empty frames should not be displayed

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#548]
It's a convention in the module that we avoid displaying empty frames. Currently they are displayed:

<img width="273" alt="Screenshot 2019-04-26 at 3 04 08 PM" src="https://user-images.githubusercontent.com/30220768/56789591-d7d29100-6834-11e9-9f0a-65ceda01dd57.png">

**Comment by lumos309** [comment]
Fixed in ENV PR (#542).
