### ISSUE TITLE
Travis runs tests twice...

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#579]
Due to #575 

![Capture](https://user-images.githubusercontent.com/43642522/59077751-7b23c500-890e-11e9-8a94-4302ffbacef3.PNG)

**Comment by rrtheonlyone** [comment]
okay we will look into this! Thanks for pointing it out 👍

**Comment by jiachen247** [comment]
Opps yes this might be a bug!! I was under the impression `test-coveralls` was testing coverage and not actually running our tests.
