### ISSUE TITLE
ENV: visualizer cannot render lists

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#605]
The visualizer cannot render lists. Hopefully this can be fixed in the future
![broken_list](https://user-images.githubusercontent.com/43642522/59748645-1cffc600-92ae-11e9-8dcc-5f8a6cad34fc.PNG)

**Comment by martin-henz** [comment]
Postponed for now. Keep the label "_postponed" and re-visit after Sem 1 2019/20. See wiki on policy on postponed Issues.

**Comment by martin-henz** [comment]
Currently being handled by project: SA 2021 Environment Visualizer
Simon and Min Yih

**Comment by seanlowjk** [comment]
May I know what is the progress with respect to this issue? Thanks!
