### ISSUE TITLE
Making the Frontend more Developer-Friendly and Maintainable

### ISSUE THREAD

**Issue by rrtheonlyone** [source-academy/cadet-frontend#608]
As I was deploying, I realised there are some aspects which can perhaps be improved upon. This issue will serve to document some of these possible improvements and track their progress.

Any sugggestions or opinions can also be listed below. The aim is to make this project easy to setup and work with for newer developers.

Current Improvements that can be done (in my opinion):
- [ ] Documentation : improve `README.md` + seperate `/docs` folder for more information
- [ ] Upgrade outdated libraries 
- [ ] Check CI and make sure its well integrated
- [ ] `package.json` cleanup - Remove some of the unnecessary commands and bash scripts
- [x] Update links to Forum etc.
- [ ] Look into linting - `npm run format` looks like it only runs prettier

**Comment by geshuming** [comment]
tslint should have default severity set to warning level so that compilation will not fail while running the dev build. Of course, tslint will be set to error level for prepush check and CI.

**Comment by geshuming** [comment]
We can consider migrating to eslint as [tslint is getting deprecated](https://medium.com/palantir/tslint-in-2019-1a144c2317a9). 

[How to setup eslint for a react app in typescript](https://dev.to/benweiser/how-to-set-up-eslint-typescript-prettier-with-create-react-app-3675)

However, `typescript-eslint` currently supports `typescript@>=3.2.1 <3.6.0` .

**Comment by jiachen247** [comment]
Whats the status of this? @rrtheonlyone @geshuming

**Comment by chownces** [comment]
Closing this as the current CI and pre push hook addresses this.
