### ISSUE TITLE
DEBUG and ENV: should only be activated for Source §3,4

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#616]
The environment model is needed for understanding this, so we should limit the use to Source §3 or later.

One "easy" way may be to allow for gutter click only when Source §3 or §4 are active.

**Comment by podocarp** [comment]
However, I feel like a debugger is useful regardless of where you are in the module. Perhaps we could enable the environment visualiser with 3 and 4 but leave the inspector as it is?

**Comment by martin-henz** [comment]
The current INSPECT tool also uses the environment model. We are working on an inspector that operates on the substitution model. Yee Jian is working on it. We hope it can be ready in time.

The idea is to use the same entry point: A break point in the gutter of the Ace editor. If the user chooses Source §1 or §2, the substitution model inspector is used, and if the user chooses Source §3 or §4, the environment model inspector is used.

If a student is curious about the environment model before the recess, he can switch to Source §3 and play. There is nothing wrong with that. However, it's clear that its not covered in class yet. 

So yea, I differ from your view. I feel that the way to activate the INSPECT debugger is to choose Source §3 (or §4). Users who choose Source §1 or §2 should not see the debugger. (If Yee Jian succeeds, the user will see the SUBST inspector, and if he does not succeed, we will not have an inspector for Source §1 and §2.)

**Comment by seanlowjk** [comment]
Fixed by #661
