### ISSUE TITLE
SOUNDS: namespace pollution

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#619]
The sound library introduces many (often irrelevant) names into the Source Academy.

Examples:
``color_white
distance_between_squares``

These two examples come from the sound library `soundToneMatrix`. These variables are currently turned into global variables with value undefined, regardless of which Source is used and regardless of what libraries are loaded:

<img width="424" alt="Screenshot 2019-06-24 at 3 29 51 PM" src="https://user-images.githubusercontent.com/30220768/59999815-76446c80-9695-11e9-9aab-20a3f09e365c.png">

We need to look at all SOUND libraries and make sure we expose only relevant names:

``microphone.js
 riffwave.js
 soundToneMatrix.js
 sounds.js``

**Comment by martin-henz** [comment]
This issue will be gone when this issue is handled: https://github.com/source-academy/js-slang/issues/255

**Comment by TheRealRavager** [comment]
Unable to replicate this issue on master. I believe it may have been fixed by other commits.

**Comment by martin-henz** [comment]
Yes, this is resolved.
