### ISSUE TITLE
Limited scrolling on the right side of Playground (REPL)

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#642]
See here:

https://drive.google.com/open?id=1Sj65P1y47ht6Rmf90w7t3EfCyqa6MuN3

**Comment by geshuming** [comment]
I did that intentionally. My idea was that the content (the div) shouldn't be completely hide-able, so it has a minimum height of 25%.

**Comment by martin-henz** [comment]
This is unnecessarily constraining the users. For example, as instructors, we find ourselves in situations where we want to minimize the display in ways that focus the student's attention. often the intro section "Welcome to the..." is not going to be the most interesting part of the display. Especially when dealing with runes, the screen space of the REPL is valuable, and we want it as high as possible.

So let's go back to the old way, where the REPL can occupy the entire height of the editor.
