### ISSUE TITLE
display primitive currently broken

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#643]
<img width="496" alt="Screenshot 2019-07-01 at 9 37 41 PM" src="https://user-images.githubusercontent.com/30220768/60440951-8eddf500-9c48-11e9-9430-bbd12e9ed0a6.png">

**Comment by geshuming** [comment]
I cannot reproduce the bug

**Comment by martin-henz** [comment]
Oh, was playing with display in js-slang and pushed a PR. Forgot to reset to master. So sorry!
