### ISSUE TITLE
Remove icon hover tooltip

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#671]
As discussed with @martin-henz,

All icons in source academy should not have a htmlTitle appearing on hover. 

For reference: https://blueprintjs.com/docs/#core/components/icon.props

Example: 
![Capture](https://user-images.githubusercontent.com/43642522/60754477-1abe9b00-a014-11e9-9107-6858d2902fe9.PNG)

**Comment by geshuming** [comment]
This issue will be fixed when we migrate blueprintjs/core to ^3.0

**Comment by alcen** [comment]
Fixed by https://github.com/source-academy/cadet-frontend/pull/685
