### ISSUE TITLE
All stream functions are undefined

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#676]
![Capture2](https://user-images.githubusercontent.com/43642522/60763489-75a1d200-a0a8-11e9-9f3f-cb9eba0d1a2b.PNG)
![Capture](https://user-images.githubusercontent.com/43642522/60763490-76d2ff00-a0a8-11e9-9112-4b70e2d76c04.PNG)

**Comment by openorclose** [comment]
They have been removed as a library, and are going to be added in js-slang in chapter 3

**Comment by martin-henz** [comment]
Yes, that is part of the library cleanup.

Streams are covered in chapter 3 of the textbook and therefore need to be part of Source §3, in the same way as lists are part of Source §2.

For the SWS3012 edition of Source Academy, we make do without library support.

**Comment by martin-henz** [comment]
This issue in js-slang covers this, so I'm closing this issue.
