### ISSUE TITLE
From 2018 team post-mortem: Profile page which can look at all the missions, all the grades, all the xp

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#681]
*Note from Martin:* I strongly support this. I think this is a low-hanging fruit, and one of the strongest reasons for having such a system: Give students a dashboard of their performance. The students should get reassurance that they are making progress in the module. So yes, I would rank this item as high as the removal of JSON from the database.

**Comment by martin-henz** [comment]
I think this issue is still relevant. Any thoughts, anyone?

**Comment by Aulud** [comment]
Addressed by #813, #854 and #898.
