### ISSUE TITLE
From 2018 team post-mortem: Make a client side grader that allows students to check their paths

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#682]
- Having this also allows us to use the same thing for aid in mission grading
- Ideally refactor this in a way that can be used both in an AWS instance and in a browser
- Grading of Paths
  - Currently students are not able to grade programming paths

**Comment by martin-henz** [comment]
Is it fair to say that we have this now?

**Comment by geshuming** [comment]
Yes we can write public test cases!
