### ISSUE TITLE
From 2018 team post-mortem: Code duplication between student workspace and grader workspace frontend components

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#683]

**Comment by martin-henz** [comment]
Can anyone comment on this?

**Comment by geshuming** [comment]
Need more info.

**Comment by martin-henz** [comment]
@thomastanck : Do you remember what this is about?

**Comment by geshuming** [comment]
Oh i understand. The source code is very similar for `AssessmentWorkspace` and `GradingWorkspace`. This violates DRY and is very troublesome to maintain.

**Comment by thomastanck** [comment]
Yes, thats right. I think one of the previous maintainers was the one who brought this up

**Comment by alcen** [comment]
Duplicate of #229

**Comment by angelsl** [comment]
Closing in favour of #1555 (duplicate).
