### ISSUE TITLE
From 2018 team post-mortem: Improve grading interface

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#684]
- Next semester avengers will be grading their own groups, so if the frontend grading tab groups by their studio, it would be neat.
- Student cannot see name of avenger
- Avenger cannot see name of student

*Note by Martin:* Strongly agree. This is high-priority, on par with the other top items.

**Comment by martin-henz** [comment]
Is it fair to say that this is handled?

**Comment by geshuming** [comment]
I don't think this is relevant anymore. So far, our build allow Avengers and students see each other's names.

**Comment by martin-henz** [comment]
Tx for clarifying
