### ISSUE TITLE
Debugger: Unclear how debugging works?

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#688]
It is unclear to me how the debugger works currently.

I am assuming that the debugger stops before the highlighted line is executed, pressing resume will execute the line, and pressing resume again will finish the debugging process. 

In that case, can we make it clearer that this is happening?

**Comment by chownces** [comment]
Closing this old issue. For future reference, the debugger pauses the program just before the breakpoint. Pressing resume will jump forward to the next breakpoint, or terminate the program when there are no more breakpoints left.
