### ISSUE TITLE
Chat: Do some basic error catching for invalid tokens

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#689]
![Capture](https://user-images.githubusercontent.com/43642522/60787230-ab6bb700-a18b-11e9-8837-2f0009fdd6ae.PNG)

**Comment by martin-henz** [comment]
Can this crash the system? Where can invalid tokens come from?

**Comment by geshuming** [comment]
Yes this crashes the frontend. Currently it happens because I did not supply a proper instance locator, but I think it can happen if a token is invalid, or if the chatkit server does not respond.

**Comment by flxffy** [comment]
I have made a pull request #694 addressing this issue.

**Comment by martin-henz** [comment]
I see. great!

**Comment by martin-henz** [comment]
Addressed by https://github.com/source-academy/cadet-frontend/pull/694
