### ISSUE TITLE
Playground editor reports incorrect line number for errors

### ISSUE THREAD

**Issue by Aulud** [source-academy/cadet-frontend#690]
The interpreter in the Playground reports the incorrect line number for errors (see the yellow box). This issue occurs in the development environment with all chapters of the Source language.

![](https://user-images.githubusercontent.com/44989315/60793841-11ac0600-a19b-11e9-910c-220aba4e8128.png)

**Comment by geshuming** [comment]
Would you be surprised if i tell you this is because the error doesnt occur on "line 3 of your code"

**Comment by martin-henz** [comment]
This issue also occurs when the function error is invoked by the user program:

<img width="530" alt="Screenshot 2019-07-08 at 11 50 27 PM" src="https://user-images.githubusercontent.com/30220768/60824361-0e853a00-a1dc-11e9-923a-3eb021061db5.png">

**Comment by martin-henz** [comment]
Handled by: https://github.com/source-academy/js-slang/pull/285

**Comment by tysng** [comment]
Hi team, thanks for the fix. However, when the error occurs in the invocation of a pre-declared function, the line number in the error message can be very confusing/misleading. Is there a way to better represent this?

<img width="1316" alt="Screenshot 2019-09-10 at 12 04 05 AM" src="https://user-images.githubusercontent.com/42670338/64547630-88ae7800-d35f-11e9-8fe2-82f7feb6d0cb.png">
