### ISSUE TITLE
Bump react/redux dependencies together

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#691]
| Package | current | wanted | latest |
| - | - | - | - |
| @types/react-redux | 5.0.21 | 5.0.21 | 7.1.1
| @types/react-router | 4.0.30 | 4.4.5 | 5.0.3
| @types/react-router-dom | 4.3.3 | 4.3.4 | 4.3.4
| @types/react-router-redux | 5.0.15 | 5.0.18 | 5.0.18
| react-ace | 6.4.0 | 6.6.0 | 7.0.2
| react-mde | 5.8.0 | 5.8.0 | 7.6.2
| react-redux | 5.1.0 | 5.1.1 | 7.1.0
| react-router | 4.3.1 | 4.3.1 | 5.0.1
| react-router-dom |  4.3.1 | 4.3.1 | 5.0.1
| react-router-redux | 5.0.0-alpha.9 | 5.0.0-alpha.9 | 4.0.8
react-scripts-ts | 2.17.0 | 2.17.0 | 3.1.0
react-test-renderer | 16.4.2 | 16.8.6 | 16.8.6
react-transition-group | 2.4.0 | 2.9.0 | 4.2.1
redux | 3.7.2 | 3.7.2 | 4.0.1
redux-saga | 1.0.0 | 1.0.5 | 1.0.5

**Comment by angelsl** [comment]
We're up to date now.
