### ISSUE TITLE
SOUNDS: current ADSR only squeezes the "release" phase

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#711]
according to the duration of the sound. The other phases remain un-changed. As a result, the sound is cut off with a click sound if the duration is not sufficient. The proper way seems to be to make the phases proportional to the duration. 

```
function adsr(attack_time, decay_time, sustain_level, release_time) {
  return function (sound) {
    var wave = get_wave(sound);
    var duration = get_duration(sound);
    return make_sound(function (x) {
      if (x < attack_time) {
        return wave(x) * (x / attack_time);
      } else if (x < attack_time + decay_time) {
        return ((exponential_decay(1 - sustain_level, decay_time))(x - attack_time) + sustain_level) * wave(x);
      } else if (x < duration - release_time) {
        return wave(x) * sustain_level;
      } else if (x <= duration) {
        return wave(x) * sustain_level * (exponential_decay(release_time))(x - (duration - release_time));
      } else {
        return 0;
      }
    }, duration);
  };
}
```

**Comment by martin-henz** [comment]
Also make ADSR linear instead of exponential.

**Comment by TheRealRavager** [comment]
@martin-henz just to clarify, the changed adsr function would accept A, D and R ratios rather than the raw duration in seconds?

**Comment by martin-henz** [comment]
> @martin-henz just to clarify, the changed adsr function would accept A, D and R ratios rather than the raw duration in seconds?

Yes, I think that would make more sense. The ratios of A D and R would be added up, and subtracted from 1 to get the ratio for the duration of S. All these duration ratios need to be multiplied with the absolute duration of the sound to which the envelope is applied, in order to get their absolute durations.
