### ISSUE TITLE
CURVES: draw_connected_full_view cant handle horizontal line

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#718]
function unit_line_at(y) {
    return t => make_point(t, y);
}
draw_connected_full_view(100)(unit_line_at(0.5));

Does not draw anything.

**Comment by geshuming** [comment]
This is an issue from last year too I believe. The line is drawn, but the view is not centered on the line properly.

**Comment by martin-henz** [comment]
Yes, its a division by 0:

    mat4.scale(transMat, transMat, vec3.fromValues(2 / (max_x - min_x), 2 / (max_y - min_y), 0))

**Comment by martin-henz** [comment]
Fixed by: https://github.com/source-academy/cadet-frontend/pull/723

**Comment by martin-henz** [comment]
fixed by https://github.com/source-academy/cadet-frontend/pull/724
