### ISSUE TITLE
Token not refreshing nor users are redirected to login page on token expiration

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#721]
Currently, when an access token expires, the frontend does not redirect the user to the login page or refresh the tokens. 

Issue can be narrowed down to 
https://github.com/source-academy/cadet-frontend/blob/b275d8bdcb7b1c6ed765e4c775d545930a506563/src/sagas/backend.ts#L614
and 
https://github.com/source-academy/cadet-frontend/blob/b275d8bdcb7b1c6ed765e4c775d545930a506563/src/sagas/backend.ts#L630

**Comment by martin-henz** [comment]
What happens instead?

**Comment by geshuming** [comment]
Yep. This happens instead.
![Capture](https://user-images.githubusercontent.com/43642522/61261705-37499880-a7b5-11e9-8cba-926ed3b76fcc.PNG)

I will then need to manually invoke the `LOG_OUT` action by pressing the logout button.

My guess is that this action might not be dispatched.
https://github.com/source-academy/cadet-frontend/blob/b275d8bdcb7b1c6ed765e4c775d545930a506563/src/sagas/backend.ts#L630
