### ISSUE TITLE
Only students can submit: Why?

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#731]
<img width="465" alt="Screenshot 2019-07-16 at 4 46 44 PM" src="https://user-images.githubusercontent.com/30220768/61279891-8dd0ca00-a7e9-11e9-98ba-dda4827b445b.png">

I think it would be useful for staff to submit, in order to test in the live system whether the grading is all correctly set up.

Would it make the system more complex if we allow staff to submit?

**Comment by jiachen247** [comment]
I think it would be really messy if staff could submit assessments. These submissions by staffs would clutter up and confuse the grading work space.

Could you specify exactly which part of grading staff might need to check? 

I personally like this rule i think it keeps the data clean. but if really need be we could give allow admins to submit. Or a better way would just have test student accounts for this purpose.

**Comment by jiachen247** [comment]
Ideally, testing of missions should not be done on prod but on staging instead. But yes if you really think this would be helpful it definitely can be done! We gotta watch out on the backend, cause currently it allows us to mutate assessments before they are open on the premise that there are no submissions tied to them. This will change when and if we allow graders to submit before the open time.

**Comment by martin-henz** [comment]
> Ideally, testing of missions should not be done on prod but on staging instead. But yes if you really think this would be helpful it definitely can be done! We gotta watch out on the backend, cause currently it allows us to mutate assessments before they are open on the premise that there are no submissions tied to them. This will change when and if we allow graders to submit before the open time.

Two things: 
(1) We don't have a staging environment, at the moment.
(2) Even with a staging environment, the same issue arises: How do the authors test the whole workflow? Without staff submission, we would need to have dedicated accounts for mock students in the staging environment, the authors would need to log in using those accounts. All of that seems rather complex.

Overall, allowing staff to submit might be the most pragmatic option for now.

**Comment by jiachen247** [comment]
Okay I see where you're coming from prof! This feature is definitely possible just have to be a little careful on the backend! Just note that its really not best practice to test on prod.

1) We can plan to create one and do it write! Shouldn't be too much work once we get our deployment right and automated.
2) We will create student and staff accounts for this! I would argue that this would actually be closer to prod than staff submitting on prod cause you really get to test as a student.

**Comment by geshuming** [comment]
I will explore how to send all testcases if the requester is staff, this way, we can run all testcases on the frontend to test the missions.

**Comment by martin-henz** [comment]
> Okay I see where you're coming from prof! This feature is definitely possible just have to be a little careful on the backend! Just note that its really not best practice to test on prod.
> 
> 1. We can plan to create one and do it write! Shouldn't be too much work once we get our deployment right and automated.
> 2. We will create student and staff accounts for this! I would argue that this would actually be closer to prod than staff submitting on prod cause you really get to test as a student.

I agree that we should do this properly. If we have a staging system, with proper test accounts, we will catch the use case that I have in mind.

There is another use case, however: The staff member who wants to upgrade their skills. For example, an Avenger may want to work on a Quest. Not being able to save is unnecessarily restricting the Avenger and in practice might deter them from upgrading their skills and interact with the system. In the light of this, I maintain my view that staff not able to save and submit assessments is an unneccesary restriction.

**Comment by blackening** [comment]
Conceptually there's nothing wrong with testing on production, **provided there are no side effects**. A large number of systems are actually designed to that effect.

The reason for this is that testing should be done in layers. The back end, front end and their integration should be tested during development/staging. 

Content can and should be tested in production, especially since we are doing content creation on front end. This is a major student gripe actually. Why are the missions not tested? The answer is probably - it takes too long for the missions to be tested.

**Comment by martin-henz** [comment]
> Conceptually there's nothing wrong with testing on production, **provided there are no side effects**. A large number of systems are actually designed to that effect.
> 
> The reason for this is that testing should be done in layers. The back end, front end and their integration should be tested during development/staging.
> 
> Content can and should be tested in production, especially since we are doing content creation on front end (similar to how blogs have post previews). This is a major student gripe actually. Why are the missions not tested? The answer is probably - it takes too long for the missions to be tested.

I agree with @blackening on this. We need to distinguish between the system as a tool for content providers and the system as a product. A good example is the "Mission Control" feature. It is currently a tool for content providers and deployed as such in Production.

If staff could submit, this feature would serve a similar purpose: It would allow mission authors to test missions before they open. I'm ok with using the production system for that. 

I also agree that we should make the authoring and testing of missions as easy as possible. This was a severe pain point last year that affected to quality of the module.

**Comment by angelsl** [comment]
This is possible now.
