### ISSUE TITLE
Link to markdown site problematic

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#735]
Currently this link
<img width="346" alt="Screenshot 2019-07-18 at 10 04 28 AM" src="https://user-images.githubusercontent.com/30220768/61423802-c4225c80-a943-11e9-95b6-2707564908b3.png">
goes here:
https://www.markdownguide.org/

The link has I feel inappropriate references to the Dillinger company. Can we find a better site for Markdown?

**Comment by geshuming** [comment]
How about this link https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by martin-henz** [comment]
Yes, I like this one a lot.

**Comment by geshuming** [comment]
The website actually has a cheatsheet as well https://www.markdownguide.org/cheat-sheet

**Comment by seanlowjk** [comment]
Chatkit is depracated and will be removed from the system. 

As a result, this issue does not seem to hold anymore :/
