### ISSUE TITLE
Grading: Pressing "Save" should go to next question

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#739]
This is going to support the most common use of "Save": The grader is done with grading the question and goes to the next question.

**Comment by geshuming** [comment]
We could look at having 2 buttons: `Save` and `Save and Continue`

**Comment by martin-henz** [comment]
I think the overwhelmingly most common use case will be to "Save and Continue" so having a "Save" button would just clutter the interface. In the rare case where a grader wants to save and still look at the grades some more, he can press the back button.

I think the addition of the Chat has changed this use case. The chat is independent of the grade and does not require "save".

**Comment by blackening** [comment]
There's a use case for multiple saves. In particular, when grading long questions like the practical exam, what i fill up in the comments box can be a lengthy essay. (involving 9 x 1 mark deductions) 

In such a situation, i save pretty often.

Save and move to next question is used more often in short questions.

**Comment by martin-henz** [comment]
> There's a use case for multiple saves. In particular, when grading long questions like the practical exam, what i fill up in the comments box can be a lengthy essay. (involving 9 x 1 mark deductions)
> 
> In such a situation, i save pretty often.
> 
> Save and move to next question is used more often in short questions.

Our "comment box" is now the Chatkit chat, which is saved as soon as you hit return. So I suggest you just spit your comment into multiple lines in the chat. Note that the "save" button now just saves two numbers: the grade and the XP.

**Comment by blackening** [comment]
This is very painful. Actually nearly unusable. 

The first time i put the comments in, it's a single pass full of things the students shouldn't see.

For example, a list of probable errors to check for, a list of known errors. No deductions are done during that pass. After that, the deductions are done in a batch after i determine the grading scheme. 

Sometimes, i grade first, then determine that a certain mistake is common enough and go back and comment on every submission that makes those mistakes.

**Comment by martin-henz** [comment]
We decided that we bring back the primary comment box, and @alcen is looking into it.

Regarding the buttons, how about:
* Cancel: disregards edits in grades and comment box since the last save
* Save: saves current grades and comment and stays on the same question.
* Next (can also be called "Save & Next"): saves current grades and comment and moves to next question.

In the rare case where the staff wants to cancel recent edits and advance to the next question, two clicks are needed: "Cancel" followed by "Next". I think this is better than popping up a box in the most common "Next" use case: the staff wants to save and then go to the next question.

I guess a small detail, but since we are discussing it...

**Comment by alcen** [comment]
> We decided that we bring back the primary comment box, and @alcen is looking into it.
> Regarding the buttons, how about:
> 
> Cancel: disregards edits in grades and comment box since the last save
> Save: saves current grades and comment and stays on the same question.
> Next (can also be called "Save & Next"): saves current grades and comment and moves to next question.
> 
> In the rare case where the staff wants to cancel recent edits and advance to the next question, two clicks are needed: "Cancel" followed by "Next". I think this is better than popping up a box in the most common "Next" use case: the staff wants to save and then go to the next question.
> I guess a small detail, but since we are discussing it...

Currently I have implemented the "Submit and Continue" button, as well as a new drafts feature to allow local saving of grading without submitting to the database

Do take a look and see if the buttons cover all the possible use cases! I did not put in a "Cancel" button as with the local drafts, you can save your draft and not submit anything, which should cover the use cases for "Cancel"

**Comment by alcen** [comment]
This has been implemented in PR #789!
