### ISSUE TITLE
Keep chatkit component alive

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#741]
![image](https://user-images.githubusercontent.com/43642522/61427934-985aa300-a952-11e9-9604-de2f22e99d3b.png)

Issue: It's very unresponsive if the chatkit has to load everytime a user opens the chatkit, which usually takes up to half a second every time. Furthermore, we should preserve the state of the chat input.

Proposal: Keep the component alive through https://www.npmjs.com/package/react-keep-alive

This way, we maintain the responsiveness of chatkit on non-first opening of the tab, as well as preserve chat input state.

**Comment by martin-henz** [comment]
I agree. This is important. Loading takes a couple of seconds each time. A bit irritating.

**Comment by seanlowjk** [comment]
Chatkit is depracated. 

The issue is no longer relavant unfortunately. .
