### ISSUE TITLE
RUNES: Exposed function implementations

### ISSUE THREAD

**Issue by alcen** [source-academy/cadet-frontend#745]
Implementation for functions of the Runes library can be viewed freely:

<img width="955" alt="exposed functions" src="https://user-images.githubusercontent.com/49450743/61450329-67e22b80-a989-11e9-90da-8162eb22dfe8.png">

This is probably not intended as some functions (e.g. `stack_frac`) are not natively implemented using the Source language.

**Comment by martin-henz** [comment]
This is addressed by this issue: https://github.com/source-academy/js-slang/issues/284

**Comment by martin-henz** [comment]
Duplicated issues; similar to https://github.com/source-academy/js-slang/issues/284
