### ISSUE TITLE
UI: Chat should no longer show "Connecting to ChatKit" when this has failed

### ISSUE THREAD

**Issue by alcen** [source-academy/cadet-frontend#754]
Currently the Chat tabs advises users to refresh the page if it is taking too long to connect:

![chastkit](https://user-images.githubusercontent.com/49450743/61517207-493b6d80-aa39-11e9-9055-66eae024f798.png)

But with the "Connecting to ChatKit" text, users are misled to believe some process is still occurring when in reality the HTTP request has failed. Another screen should appear so users know for definite whether it is safe to refresh or not.

**Comment by flxffy** [comment]
This has been addressed in PR #694

**Comment by alcen** [comment]
Ok 👍

**Comment by flxffy** [comment]
PR #694 has been merged into master, I will be closing this issue.
