### ISSUE TITLE
UI: Grading View is loading a lot of submissions

### ISSUE THREAD

**Issue by alcen** [source-academy/cadet-frontend#755]
Currently, there is a brief delay when clicking the "Show all groups" button in Grading View, between the button getting selected and the actual content appearing:

![showallgroups](https://user-images.githubusercontent.com/49450743/61517828-be5b7280-aa3a-11e9-8201-feb984059c89.png)

As the semester progresses and more submissions are recorded, this wait will increase, and it is not immediately obvious if the page failed to load the results, or is currently still loading them. There should be a loading screen to reflect this.

**Comment by geshuming** [comment]
With pagination coming, the load time will be consistently short.

I disagree on the use of loading screens. We should actually figure out ways to load content faster, increase responsiveness and minimize features.

**Comment by alcen** [comment]
> With pagination coming, the load time will be consistently short.
> I disagree on the use of loading screens. We should actually figure out ways to load content faster, increase responsiveness and minimize unnecessary features.

Ok, I guess that is a way to solve the issue at hand

**Comment by martin-henz** [comment]
Duplication: similar to this cadet issue: https://github.com/source-academy/cadet/issues/257
