### ISSUE TITLE
Parameter Passing Defects: public/externalLibs/sound/soundToneMatrix.js Line 514

### ISSUE THREAD

**Issue by HarryShaunWang** [source-academy/cadet-frontend#758]
Function `exponential_decay(decay_period)` is defined on line 480 that takes only one parameter.
But on line 514, calling it with 2 parameters. `(exponential_decay(1 - sustain_level, decay_time))`
Even though JS will ignore this, it's better to rectify.

**Comment by martin-henz** [comment]
Thanks, @HarryShaunWang . Will take a look.

**Comment by TheRealRavager** [comment]
Already fixed by #759
