### ISSUE TITLE
UI: Improving matching parentheses 

### ISSUE THREAD

**Issue by TobiasWrigstad** [source-academy/cadet-frontend#761]
The highlighting of matching parentheses is *very* subtle: 
<img width="195" alt="bild" src="https://user-images.githubusercontent.com/364888/61760901-9041ae00-adff-11e9-9f64-6fc692388bff.png">
It needs a better highlight, like possibly changing the background colour of the character. 

Also -- I suggest adding something like the Emacs rainbow-delimiters mode which colours the matching parentheses in the same colour for improved matching:
<img width="501" alt="bild" src="https://user-images.githubusercontent.com/364888/61760978-d860d080-adff-11e9-9b6a-55ff7bb0e099.png">
Image above also shows the clearer highlighting of the outermost parentheses.

**Comment by martin-henz** [comment]
@jiayushe @ccyccyccy can you take a look at this?
