### ISSUE TITLE
cadet frontend README: step missing

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#762]
Currently we say:

1. Install a stable version of NodeJS (tested: Node 10.15.0).
2. Run npm install to install dependencies.

We should say:

1. Install a stable version of NodeJS (tested: Node 10.15.0).
2. Clone this repository and navigate to it using "cd" in your command line or shell tool.
3. Run npm install to install dependencies.

**Comment by Aulud** [comment]
Resolved by #918.
