### ISSUE TITLE
Mention recommended browser, Chrome, somewhere

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#768]
We should mention that we recommend a particular browser, Google Chrome, version..., somewhere.

How about the following for now, before we take a closer look in 2020, along with a mobile and tablet friendly interface:

Welcome to the Source Academy playground!

The language Source is the official language of the textbook Structure and Interpretation of Computer Programs, JavaScript Adaptation. You have never heard of Source? No worries! It was invented just for the purpose of the book. Source is a sublanguage of ECMAScript 2016 (7th edition) and defined in the documents titled "Source §x", where x refers to the respective textbook chapter. For example, Source §3 is suitable for textbook chapter 3 and the preceeding chapters.

The playground comes with an editor and a REPL, on the left and right of the screen, respectively. You may customise the layout of the playground by clicking and dragging on the right border of the editor, or the top border of the REPL.

As of August 2019, we recommend the browsers Google Chrome, Version 75 or higher, or Firefox, Version 68 or higher, to visit the Source Academy.

**Comment by jiachen247** [comment]
I think chrome of firefox is fine also! but yes Chrome shall be our first class/supported browser!

**Comment by martin-henz** [comment]
I've added Firefox: 

As of August 2019, we recommend the browsers Google Chrome, Version 75 or higher, or Firefox, Version 68 or higher, to visit the Source Academy.

Would that be better?

**Comment by jiachen247** [comment]
![image](https://user-images.githubusercontent.com/17170991/62029206-9c20dc00-b214-11e9-9da0-ee7c5a7a2eb0.png)
How about in the help area?

**Comment by martin-henz** [comment]
OK, so we could say:

Help

As of August 2019, we recommend the browsers Google Chrome, Version 75 or higher, or Firefox, Version 68 or higher, to visit the Source Academy. If you encounter issues with the Source Academy using these browsers, please use the following resources.

* ...
* ...
* ...
