### ISSUE TITLE
ACE: "too many errors" message for correct program

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#771]
Here is an example:

https://sourceacademy.nus.edu.sg/playground#chap=4&ext=BINARYTREES&prgrm=PQKgBADgTg9gVgUwMYBcBcYBMAWMBxAQwFsEAoMC6eZFMEogIwSgGcMAZAVxjAE1OAdgAsCMADRgAWiIEBzMAGsEAT04EB5CgBMCKBBkwAGAIwBOAHQB2c5ktgAyrs0UwKIQjAEANrJhQAlm5EYDAAZljYALQQMP4CKCxgSN5InF66-jAC5mAAKu50BHFg-loIBM7%2BiShQynHy3l6uBTEsLP4MXh5IMIxxGVmeAlpgoXFa9Z5eTc5uHgGyQrQsMF6cKJnZeS2x8SWJQjAA7q48Ze2yAp5gR1UezkcEyqclAkhrZVNNc2DtKGobQa3NwwdZDZ69KrtLKkEDAUg9AQsWgELQjAC8YAAFAAPCTKACUYHRAD4wDiwABqMDKADcCKyyLocU4iUxuPxRNJ5LAkRp9MRTI2JGJ2LxNK5ZIp4DpDKRtAmADdRRyJcSpWBgPy5UyYidMURdEIAPp6gWM2gwCCirxVFBY1FaCREFksCTChASJUE83yyBFKDG21MzHB%2B0QANYwxiQwEiQR-xQKNiYxx-2JrHGGNphNJrOp%2BORzApgk%2B0ikLq0ULpeSY0LeFgIemkUKCVCbJJZRXMFCmgJ%2BQLKY1hYcQZgDARY1sCIkAb2cYCgCH%2BUCuU8ExPRmMdYAAPrvRhutwbXQSFy4wAB%2BMCGc8uDDGekAXxbbcBVwY-VqxuSXlS6XfLEBE4Igs0PAQJGAohMDnBdgC1FAeF-f9dA8LIvGeFAjh4KCmFYBclxXK5pyAkCwKgmDn3Lad20GAQEBxXsrXHQCvGRWCL3gl5kLSVCwHoxjO2GQJNgXQVaCXbtWAQIM7VFSTmEbLE2JQMsL38cIsXcVEsQU6TZPYqkwGMTdMWwDiLxcQjOFXTwIDHYYgIYpixygCcsTvSyvO8vSlJQIovF0hApMbAzVNLCRPO86KYrAMMo1LekLxfC8EDYjx52i6zbN8hAHXshBHPi7StCCkKZLDIlqQLMAoti%2BrvP8-xAtysLSzUlwXxfai3w7WRCpYmSCFHFjNjCrE4rkucKGcGj3zACZZECY1EJGtzAIW-wltoCyvOyq4w2NJdQixK0xEWwIOrAFKKH2woICxC7e1W5j1o7CRKqonq3nmhhOGarRjU-AQCG-GoEDyybkWHUI1onCRNS1QACeUAX8VAAdTQAQtzDOqGu8w6R1w5gxBx3HLNzGHhygMooDAXahKZUIQzAEqsXJkc-Gpq76eWYZRSawK2dhjnmC5hc5o7P6AaDcoToEGAymm2roq4w0lGuQmabiRDrnBsgsuXGyrlVmTdaA%2BXPUKJRjQQIgIBQIdTbTY3rdt%2B2VqXPLEoXG6ZovcXBjGVhe2B0GHY9rE6YvcT%2BJA92IdFQ0HopblJa8QGugIE6cTTfHYY1rmo4tEIIBM0M7SOhATtzuH3wkWMku86OrUwG1y%2BO5Ty-Z1z4eMguXCbiAAGZW%2Bh9vq9envKKipuqeYUvmfKUrBcpzmG68mfqZbzF%2BdZgMKeFqA%2B4oAfjDjjwDQIK3TatMCSdJlxDvbqCz4kA%2BCzv%2B%2Bod7J-Y911-Z6gCZaqXtooD0wGfFUb9TIhAATBD%2B99rzO2vhAYs8DP6xRvi-JW6CcEXkfpXUiRAsFQOpDBM8uCYoYCQeHZuxMKEUPwbLX%2BHt-7UxMnyd%2B9DcGYN1kfbB68i5WkHhA9kB8t5bhvESNBuNEGXxNjQoekUuGk2blgxhhCsHSOUTFLocg3AaN4byXu5DtH3ktvIiGp1FH8NMdFdRz8-6SNfigs%2BfC7pCLPmva6C4xa9UGI2REgMQ5g3DpHfuRcHEewTgQJO6owCp3TjLXEOdO55xAnhPhJ8R7fwIePbutdJFeMLn6Zu2SK5V1STXTYEhUxFPCSUoeZSx6VIngUqeoDBElxEeYs%2BVjb62IoPY5hEM64pNHgQyJIzjF1OPp04RutolXwUYPJRAyhlEMcTBD6bcJnDItoPEBjdOngIWRfJZljSnONPo4jxvCZmLgNrZVRusvHdXUppRmtBjw3jAAAMl%2Bb8Xm3zUxgEyj5R5VwAlZCCV%2BMOliuY%2BzAGlRsoKop3UDtDYJcLPavNIN1f2VxdY-hSLxQChiwUUA0tiKoLs7bYuUpXYObk3hCCxLwok-yoo0ptnS3pCwlhA2ZUgVl7LPJhL2hCpF8Rahso9gigZn8FzIoymiyVWLiV-lJZsDyCrXAew1ShVijLBXqGFbKiGEUbGmMKjUZQ5qEBpi0Q1IlPEALav5Uy01Iq5VOvqiY3VFAEV4vLFxAlYB%2Br0XWjJcm8UY12gJPOLilk7qkC4t1UNfirjCvUP1GufhlLsQpbVNN31aJGyKAIY0ZQxj0UBgfU0kYv4Uw1oWRM%2B8AFgFWRg-JfhjTPzDJ2h5ABHf6S5jTqBYEcZgvt6qsOYA2ttA7B0zlBTYriAhADHcoACwjAANzoACnU91xuRIAGcTABG6RjQANN6AAPFQAVHK5gkIAXCVADTmoALjlbyWTDY2Xs1YCCyHdpwT2Raf21j1QB3FF4xKdJYr2gdmII2DXHVUrI41i7QcDP2qaXiw2utZNiVpMG7QI2ri231F5l4H0HUuEdiYhpIinYfVFHS-SnPif9NOQNYW9Pw4GMMdCuHEfSUTUjLhyMAL4dhrsPYVowGtjiaACA2jascSuot0Uw00qgmy8VMU7oacE0mG1Mrwr3OSnfCTttQbRv7AEe29rjQsE4BAd0%2BqHMMG00xpkVp7OOdFIiKSvZoCZBs0OLuo0shYkM3aolDmICHNJgPbzDBfOSagAF6zg5975O1ZFuzrm4u42jiXUULNROr2kYVrergAq7zbezMTJnvJUtZqXCRhg-kApQdAkFqn75Na865sAZJ%2BuOfc-fO6fmpOrQYvJxT4XoucAYJBIxtTSOIs-sqxjyi7oACIsTbaMsJ%2BqE3UvSdkzN6Ek55uLf4stqqh2YrbYJNthrsU1v1Te7FDbPXSZNasd560AAeYuiWiT7itbgv7MXoHDaS-88HXCgJdavNiIr3zYx7gPEVgHmJOsYE62j9qm3bHjZS89GT02lyzcuy5hbS2OF8M-h93GX37sPKImAXb%2B3qSs6Y-507FOFMXdy7Tm79OqQ868o957q3pFM9Mw1CTAg%2BetO1dOUbXkmvTmgY6dXOnJXbcpNLxn0iNua6PBIl0wEWC6-1uz7bkQjf3zl95U3Hzzfb38CQG34K7cgEd6TZ3XkWcUJ28Af3uNA-eIak1vTRB7WliJ7jO6yIAhyA0nanL7KXtR-qsH3rmlY8MtCJ6ll8eOW-NI4Xj1JrS-su97FZPNR6jp4i9Ku1XRi817NXXg7AahLK6y%2BFzPcq7t95T830IGe2%2B6S2gKhgQrvUWvyw1SPqV0olALywPtIEi8l%2B7yP%2BvF5G%2Bp6WpP1vtrd9d8Xw6hPlIJfHZcmFycw%2Bl-i9sT0CzY7AsDls446v8%2BvUy9s95d75XdqUt9NN-8F8y9D8j9JUP8Iwv90tf8WE4pjUADa8R83939SckNn9p92VsDTFx808z8csoDAC69gDOoTd19vsk94DehECrMgtBx7UPp0DoDCC78BkH88Dz8jMsCeCcDP8WCf8otUCKDMCl9qCKAnwcE74mcmdo4J16M%2BZ9VXV3I7kuUTpDQ3Bx0GAWAHQ6Np0%2BQqNR1aNJ0RYwBscbxzBDAHDHCTBdcuJAAyb0AAgVQAQ3NAA3uRijvgmBYAgHSDtT4Kmzk0pyF02WX28i-WNGA3-RxTvjukfCiiZzzwb0lRSOikRURQXCa3UVQ3Wl7QwyZFGWgWHk5TsR2ROkKN0GKNjgHRqS5AkQqIryqPGRqO423yIUaKwGaMxGHkDQXHoJwyMK6N40GUqRI2UVK2nQkHMJo3HRMMPnuTuhu2%2BWwCimvGMgoC4kAA28wAEujcxABuA0AEdFQASHNAAUuRvSiiigwEKDiCrUrjiAQDrQAQXSTCbQJn0y7T70mI6NOneKPRQCW2AV%2BL%2BPimjChKJHBL7wWLHVUKJnh11XrWBOXSMhMiDTXxRRGJJTWDGJ7R40I3%2BKYjSUYCExmL3jq2pkowQGowROWIZ1JlVXZweMrWrReLeOpg%2BImgE3JKgFbUDGpLmORIEkfzenC1qMQnQwaPjVpPpMsPoznUDDRKWyDXxUzX2G6LwnGj5IySA01Njx1LDGMF5KmP00HV0VkDcFpm%2BzDQAC9mAZIlRSgZIGAhwNYJp856C1i2stQNZoE2taQbEmcNIGU9EhBjx0d6C4D2cagwNUiop0i9dWTHSx0XSyggYPT9MzSAS9SiYrS3BIgQVaY0FrwjT50TTczSTtSRTCyhBltSz74MB6x0p7kciINOyrJJUKyiTkRTT8yBT6yO5oZvj%2BSvYNSfoOwED1h51VpRiI4i1o4NZ55EDQotZWZYBXY9scB8BiAPBkRQYEgABCMAAABQzhRRtWnR%2BAxVoC1gQH6igG2wXDTGMHrkgz9A1kqzXJkg3KoG3O2wvPKCvPiBvIKChV5gfKfMexqQ-OKSZA1mHhx1BnXPiE3KYPtCAsvI8GvJph%2BDcETBGGguYFguMngvqUQv01wBQv0n-K3Ltj22AoIFAr0HwoKFCFBFSwbIfKgBgrfIopsU-KZCSzLmREITwnIn02LBjn5JWVkrwnMiKTDN7PGjc1tLqkNEeI5NrRXnnVzCxEWwMuhMtLtGTBMokF3IRlVMKTqjDOAwTRZMNg5wAEFpgHBVh1hNhEhLMHBDgjgBBjzw9LI5dlUYzYznLtsAA5HgewTy98IKkzNbNbMKuqHbAASSV28FKDAEyogHWESvPFyO6gZFtlnMDHnLxNZAjmbHLDqvqoasasaqAA

The message is here:

![Screenshot 2019-07-29 at 6 01 52 PM](https://user-images.githubusercontent.com/30220768/62039927-2ecc7580-b22b-11e9-9c4e-188e443f82a3.png)

**Comment by ccyccyccy** [comment]
The error is similar to this one https://groups.google.com/forum/#!topic/node-red/l9dlJzoxBOk
Seems like JSHint have problems with too many undefined variables such as `list` and `pair`, and when there's too many errors ( default should be [50](https://github.com/ajaxorg/ace/blob/fff9a8e2596270ef1189f4d8af91711700a3dda0/lib/ace/mode/javascript/jshint.js#L7072) ), the error message will show.
You can put "use strict" to see all the errors:
![Screenshot from 2019-07-31 23-55-09](https://user-images.githubusercontent.com/32454748/62227622-d645d580-b3ee-11e9-8f6d-18e8e94ae081.png)

**Comment by martin-henz** [comment]
That site that you mention has a few hints how to solve this, such as increase the error threshold:  /*jshint maxerr: 100000 */
