### ISSUE TITLE
Bugs due to Redundant Breakpoint feature in assessmentWorkspace

### ISSUE THREAD

**Issue by jiayushe** [source-academy/cadet-frontend#772]
Breakpoint feature is enabled in assessmentWorkspace but Inspector tab and other supports are not available, resulting in weird bugs in frontend.

![image](https://user-images.githubusercontent.com/42549358/62047727-c5099700-b23d-11e9-932f-3cf389f206fe.png)

**Comment by jiayushe** [comment]
![image](https://user-images.githubusercontent.com/42549358/62048144-b2439200-b23e-11e9-9683-e432d965089f.png)

**Comment by martin-henz** [comment]
> other supports are not available

What do you mean by "other supports"? Would it be possible to support the debugger and inspector while in assessments? In principle, I don't see why we shouldn't be able to do what we do in the playground. Same for data visualiser.

**Comment by geshuming** [comment]
Issue here
https://github.com/source-academy/cadet-frontend/blob/0dc69f3c15fa73f335a3994bcd29c8934d5cea38/src/sagas/workspaces.ts#L345-L347

leads to "always true" condition when chapter is <=2
