### ISSUE TITLE
Create Invalidation with CloudFront after syncing with S3

### ISSUE THREAD

**Issue by jiachen247** [source-academy/cadet-frontend#780]
After deploying a new version of the frontend it would be nice to invalidate the cache `/*` on Cloudfront.

**Comment by martin-henz** [comment]
Is this a deployment workflow issue? Can you change the deployment handbook accordingly?

**Comment by jiachen247** [comment]
Hi prof, sorry missed this but yes just included this in the deployment handbook! All's good! @martin-henz
