### ISSUE TITLE
Migrate to react-scripts

### ISSUE THREAD

**Issue by alcen** [source-academy/cadet-frontend#805]
"react-scripts-ts" is depreciated, as Create React App now supports TypeScript natively:
https://github.com/wmonk/create-react-app-typescript

Many upgrades like the newer versions of Webpack are supported by react-scripts, so we will have to do this to ensure bugs are fixed

This may not be an easy task, as react-scripts enforces the use of ES modules instead of CommonJS modules. Changes will have to be made to the TypeScript files

**Comment by angelsl** [comment]
Done a while ago.
