### ISSUE TITLE
Overall structure of Source Academy UX

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#81]
**Current structure**

Cadet | DEVICE                                                    </> PLAYGROUND

Under "DEVICE":
Missions | Side Quests | Paths | Contests             Announcements |  Materials | Profile

**Proposal**

Source Academy | News | Material | Playground                           <USER_ICON> Thomas Tan

Under "Source Academy":
Missions | Side Quests | Paths | Contests

Notes:
* "Materials" renamed to "Material" (that's grammatically better, see https://english.stackexchange.com/questions/247497/material-vs-materials-which-is-correct)
* "Cadet" renamed to "Source Academy"
* "Announcements" renamed to "News"
* The <USER_ICON> could come from the IVLE student picture.
* Clicking <USER_ICON> or "Thomas Tan" will take the users to their Profile
* Before the first login, there would be "Login" instead of "<USER_ICON> Thomas Tan"
* I'm assuming that we treat News, Material and Playground as public information; anyone can see this without login.
* Before the first login, the clicking of "Source Academy" is disabled, and no Missions etc are displayed.

**Comment by martin-henz** [comment]
The toplevel could also consist of pictograms:
Source Academy | News | Material | Playground <USER_ICON> Thomas Tan
-> (for example)
* ![](https://sourceacademy.comp.nus.edu.sg/images/logo.gif)
* ![](https://www.imca-int.com/wp-content/themes/imcaseventeen/img/imca-icons/post.svg)
* ![](https://www.amd.com/system/files/11050-partner-marketing-materials-icon-960x458.png)
* ![](http://www.fullbasketproperty.com/uploads/amenities/b9026fbb68aac397c6615e0a9a9cedb4.png)
* <USER_ICON> Thomas Tan

**Comment by remo5000** [comment]
Sounds good!

**Comment by remo5000** [comment]
I think a combination of an icon and the word works well.  I have added the admin and game buttons as well (as they have been scaffolded). Is this something like what you had in mind? @martin-henz 

![image](https://user-images.githubusercontent.com/12512488/40961325-d474eba8-68d4-11e8-8dfc-c93d5df55d4b.png)

**Comment by remo5000** [comment]
@martin-henz 
- We shall address the space issue when resolving #76.
- The Game button is for the "story". I can move it into Source Academy.
- The article makes a lot of sense, I'll remove the all caps. Thank you for the feedback! 😄 

One question: Given that the back end models refer to "Announcements", could we keep that name instead of "News"? This would allow the button to match the filenames, making it clearer in terms of software design. The visuals, front end and backend would then be consistent.

**Comment by martin-henz** [comment]
Regarding the "game": In theatre, we call it "breaking the fourth wall", when we remind the audience that they are sitting in a theatre. In the same way, if we say the Source Academy is a game, we want to immerse the audience in it. So ideally, the game should be the default. So how about taking the users (who are authenticated) by default to the game. Then they can escape the game using the buttons. But the "home" button, called "Source Academy" at the top left takes them to the game. Once they are in the game, they can "escape" in two ways: They can choose a top-level item and escape their identity for a while, by going to "Material" or the "Playground" or they can choose an "in-game" item by going directly to a "Mission", "Side Quest" etc.

**Comment by martin-henz** [comment]
(maybe we can discuss during the meeting on Saturday)

**Comment by remo5000** [comment]
@martin-henz I have made the changes you requested, it looks like this now! Kept the upper case on the title to make it prominent.
![image](https://user-images.githubusercontent.com/12512488/40975165-9d12b7c6-68fc-11e8-9393-eb638b09e363.png)

You make a good point on the "fourth wall"! I feel intuitive UX should have a clear "path" to get to a certain display/state. Perhaps we could rename the button to make it immersive, in the sense that it isn't an offshoot from the idea of a "Source Academy" e.g "Spaceship". That being said, looking forward to discussing this further during the meeting 👍As for now, is the above layout alright?

**Comment by martin-henz** [comment]
What if the "Source Academy" button takes you to the current game state _and_ shows the buttons "Missions", "Side Quests", "Contests"? What if that's the default view after authentication? This way, the game would be the default, but opting out would be very easy: just click on any of the buttons.

**Comment by remo5000** [comment]
@martin-henz Ah I see your idea a bit more clearly now. We've implemented it in #85 (commit is above), thank you for the feedback once again!
