### ISSUE TITLE
Navbar Contributor button flow incorrectly

### ISSUE THREAD

**Issue by DarkDestry** [source-academy/cadet-frontend#842]
**Issue:** 
Navbar Contributor button jumps to second row on certain width.
Button disappears when logged in as it is behind the second navbar

**Steps to reproduce:** 
1. Enter Chrome browser mobile view.
2. Set width between 902 and 770 px

**Screenshots:**
![image](https://user-images.githubusercontent.com/3728955/62992518-56a41600-be86-11e9-9c05-7c15743e5acd.png)
Button on second row

![image](https://user-images.githubusercontent.com/3728955/62992536-6cb1d680-be86-11e9-8187-0dd83f47ae4b.png)
Button missing

**Comment by DarkDestry** [comment]
@martin-henz You encountered this issue during your lecture :)

**Comment by martin-henz** [comment]
> @martin-henz You encountered this issue during your lecture :)

Yes, I was quite perplexed.
