### ISSUE TITLE
Inspect displaying built in functions

### ISSUE THREAD

**Issue by podocarp** [source-academy/cadet-frontend#843]
Try pausing within this simple sorting algorithm. The inspector is exposed to built-in functions and somehow their implementations are visible as well.
```
function sort(M){
    function swap(i,j){
        const temp = M[i];
        M[i] = M[j];
        M[j] = temp;
    }
    
    let pLo = -1;
    let pHi = 15;
    let p = 0;
    while(p < pHi) {
        const curr = M[p];
        if (curr === 0){
            swap(p, pLo+1);
            pLo = pLo + 1;
            p = p + 1;
        }
        else if (curr === 2){
            swap(p, pHi-1);
            pHi = pHi - 1;
        }
        else {
            p = p + 1;
        }
    }
    
    return M;
}

sort([0,2,0,1,1,2,1,2,1,0,1,0,0,1,1]);
```

**Comment by openorclose** [comment]
The inspector needs to add the names of stream libraries into the blacklist in inspector.js

**Comment by lumos309** [comment]
I had a similar issue in ENV, where built-in functions were exposed with any library selected.  Solved it by doing 

```
// add library-specific built-in functions to list of builtins
    const externalSymbols = context.context.context.externalSymbols;
    for (let i in externalSymbols) {
      builtins.push(externalSymbols[i]);
    }
```

**Comment by podocarp** [comment]
> The inspector needs to add the names of stream libraries into the blacklist in inspector.js

One interesting thing is also stringify isn't showing the `symbol...` output for these builtins anymore.
