### ISSUE TITLE
Wrongly shows "please login again" error messages when not logged in

### ISSUE THREAD

**Issue by tysng** [source-academy/cadet-frontend#846]
Hi Team,

Great work on the improved source academy! However, I see "Please login again" error messages both upon visiting the front page (even in incognito mode) and after a successful login. Please refer to the attached screenshot. These error messages might confuse new users.

URL: https://sourceacademy.nus.edu.sg/login
Browser: Firefox 68.0.1 / Chrome Version 76.0.3809.100 
OS: MacOS Mojave 10.14.6

<img width="566" alt="Screenshot 2019-08-14 at 3 05 45 PM" src="https://user-images.githubusercontent.com/42670338/63001095-654df580-bea5-11e9-982a-d6e3d6511e5f.png">

**Comment by Aulud** [comment]
Have a fix for this; will deploy shortly. Apologies!

**Comment by Aulud** [comment]
> Hi Team,
> 
> Great work on the improved source academy! However, I see "Please login again" error messages both upon visiting the front page (even in incognito mode) and after a successful login. Please refer to the attached screenshot. These error messages might confuse new users.
> 
> URL: https://sourceacademy.nus.edu.sg/login
> Browser: Firefox 68.0.1 / Chrome Version 76.0.3809.100
> OS: MacOS Mojave 10.14.6
> 
> <img alt="Screenshot 2019-08-14 at 3 05 45 PM" width="566" src="https://user-images.githubusercontent.com/42670338/63001095-654df580-bea5-11e9-982a-d6e3d6511e5f.png">

Have deployed the fix in PR #854. Thanks for logging the issue!

**Comment by tysng** [comment]
Thumbs up for the prompt fix!
