### ISSUE TITLE
Maintain game component

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#857]

**Comment by martin-henz** [comment]
This is being handled by the CP3108 team SA 2021 Game

**Comment by wltan** [comment]
We are currently maintaining a separate fork at https://github.com/Source-Academy-Game/cadet-frontend to enhance the gameplay experience and administration.

**Comment by martin-henz** [comment]
ok. thanks for the pointer.

**Comment by jetkan-yk** [comment]
This game issue tracker shall be replaced by the game label.
