### ISSUE TITLE
ACE: Error raised for valid string binary operations in the first interpreted line

### ISSUE THREAD

**Issue by chrisjwelly** [source-academy/cadet-frontend#872]
### Description
In the playground, when entering a valid binary string operation in the first interpreted line (e.g. `"hello " + "world";`), an error is raised. However, despite the error raised, the program still runs normally without runtime errors (because the code is a valid program, I think).

### Additional info
Seems like this only happens to strings. No such error is raised for binary operations on boolean or numbers. 

### Screenshots
Examples of binary operations on strings (Note that the REPL still shows the expected output):
![](https://imgur.com/e49ZEyJ.png)
![](https://imgur.com/or9RK8y.png)
![](https://imgur.com/79iTpaJ.png)

In line 3 (but lines 1 and 2 are empty):
![](https://imgur.com/hg2qml3.png)

No binary operations (Nothing wrong)
![](https://imgur.com/Zw6QYlk.png)

String operations that are not on line 1 (contrast this program with one of the similar screenshots above):
![](https://imgur.com/dLe7MD2.png)

A funkier example involving `||` with booleans:
![](https://imgur.com/PiySZ66.png)

**Comment by Aulud** [comment]
@openorclose Mind taking a look at this and triage if it is an issue with the Ace editor or with js-slang? Thanks!

**Comment by geshuming** [comment]
It's Ace Editor's javascript mode issue. There is also another issue with "Too many errors" due to us using injected namespace.

**Comment by chownces** [comment]
Tested the above examples in the Sourcecast Workspace (which still uses the AceEditor annotations), and it seems like the issues do not persist. Additionally, the Playground and Assessment Workspaces do not use this annotation functionality anymore, so I think it's safe to close this issue now. Thanks!
