### ISSUE TITLE
Rename "side content" to "REPL"

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#92]
If the name "side content" appears in the sources, it should be replaced by REPL. That's the commonly accepted term for this sort of thing.

**Comment by ningyuansg** [comment]
No worries, prof. The REPL is named `Repl` in the source code. The side content is a separate component that houses components such as the mission briefing, list visualiser, or grading UI (for the avengers). Altogether, the workspace has three components:

```
     +----------------+----------------+
     |                |                |
     |                |  SIDE CONTENT  |
     |                |                |
     |                |----------------|
     |     EDITOR     |                |
     |                |                |
     |                |      REPL      |
     |                |                |
     |                |                |
     +----------------+----------------+
```

The implementation of the workspace in the last source academy also had the concept of 'side content', but that had referred to everything on the side of the editor, REPL included.

We decided to have the side content and REPL separate by default as on a typical 1920 x 1080 screen, a lot of space is wasted on the right side if it is only the REPL (usually, the REPL output is cleared on execution of the editor code). 

Nonetheless, the classic layout (editor + side content, or editor + REPL) is achievable by simply dynamically resizing the workspace components by dragging on the borders.

![](https://thumbs.gfycat.com/BetterImpishFlamingo-size_restricted.gif)

**Comment by martin-henz** [comment]
I see. Thanks!
