### ISSUE TITLE
Scrollbar no padding against text in right panel

### ISSUE THREAD

**Issue by DarkDestry** [source-academy/cadet-frontend#920]
Reported in piazza

> The scroll bar always makes me feel very uncomfortable and this situation is harder to handle than those quests or missions. Unfortunately, my screen is not long enough to fit in all the paragraphs to make the scroll bar disappear(I also tried zooming out but I can't read what ants read). D:

![image](https://user-images.githubusercontent.com/3728955/64308986-beed9f80-cfcd-11e9-93f0-52668ecd6c19.png)

**Comment by DarkDestry** [comment]
The quick fix for this is to add `padding-right: 1em;` to `.side-content-text` but im not sure if that is the intended design

**Comment by Aulud** [comment]
@DarkDestry The proposed fix resolves the issue when the scrollbar is present, but now leaves the tab content container with asymmetric padding when the scrollbar is hidden.

![image](https://user-images.githubusercontent.com/44989315/64376753-8ac0c000-d05b-11e9-8543-27674b23267c.png)

The issue here arises with BlueprintJS' implementation of the `Tabs` component... again.

**Comment by DarkDestry** [comment]
Alternatively, 3 solutions exist and in ascending order of difficulty to fix
1. Equal padding on all sides - This will reduce the actual size of the text content which might be triggering. 
2. Query for when the scrollbar exist and apply the style as required. 
3. Redesign the right panel to have the tabs frame to be within the same as a REPL output. This means that in order to access the REPL output, instead of dragging the divider up, you scroll all the way down, past your tabs frame, to access the repl output. This also mean that you cant anchor the tabs ontop anymore.

**Comment by Aulud** [comment]
@DarkDestry Just a minor update on how things are going - I modified the CSS to move outward the container that introduces the vertical scrollbar.

This change aligns the DOM level at which the vertical scrollbars for the side-content and the REPL are rendered, and additionally respects the internal padding of bp3's `Card` component used by bp3's own `Tabs` component. I believe this is an acceptable fix for the issue.

![image](https://user-images.githubusercontent.com/44989315/64918131-8c615500-d7cc-11e9-9c8c-80240ecdb258.png)

**Comment by DarkDestry** [comment]
Yeah this looks like the cleanest easy fix atm.
