### ISSUE TITLE
Saving code in the editor resets the editor

### ISSUE THREAD

**Issue by chrisgzf** [source-academy/cadet-frontend#934]
### Browser:
Chrome Version 77.0.3865.75 (Official Build) (64-bit) on macOS 10.13.6

### Issue:
Sometimes, whenever you save **for the first time** while editing a task in a path, mission, or quest, the code is saved BUT the editor resets to the provided code template, even though it is saved. The saved code only shows when you refresh the page.

Note: I say "sometimes" above because I can't consistently replicate it, so I am not sure what triggers this, but I have indeed faced this problem a few times. The most recent one was with Path 5B.

### Steps to reproduce:

1. Open your path/mission/quest, and go to a task where you have not saved before.
2. Write your code.
3. Press the orange "Save" button for the first time in this task
4. See all the code you've written suddenly disappear from the editor
![image](https://user-images.githubusercontent.com/4933577/64851508-17fea880-d64a-11e9-9f99-c93c48ab0f3d.png)
5. Refresh your browser, and suddenly your code is all back.
![image](https://user-images.githubusercontent.com/4933577/64851555-39f82b00-d64a-11e9-9d16-690ad3c22a33.png)

This bug has affected some users who think they have lost their work. See https://piazza.com/class/juazn2axpf35wp?cid=291,
```Btw, the 'Save' button sometimes also reverses my work to minutes ago, lost my work once due to this. Hope that there's a solution to this....```.

It is possible to permanently lose their work when their code disappears, if they press the save button again.

**Comment by chrisgzf** [comment]
I just had this happen to me again in mission "POTS and Pans" Q1, but this time round, **it didn't happen to me on the first save, but my subsequent one**.

1. Write my code for the mission.
2. Save code for the first time (without editor resetting, works as intended).
3. Change some parts of my code.
4. Save again, this time the editor resets to my older save in (2) **(bug happens here)**.
5. Refresh browser, suddenly my intended saved version in (4) is back.

I'm guessing perhaps the editor might be assuming that the saving of the code is complete, even while it actually still in progress, and then loading the saved version (which is the older version, since the new save hasn't completed)

**Browser:** Firefox 69.0 on Arch Linux

**Comment by martin-henz** [comment]
Thanks @Aulud for taking a look. We need to triage and see who would be in the best position to root out this nasty issue. Thanks @chrisgzf for giving such a detailed bug report.

**Comment by Aulud** [comment]
> Thanks @Aulud for taking a look. We need to triage and see who would be in the best position to root out this nasty issue. Thanks @chrisgzf for giving such a detailed bug report.

We have an inkling how to reliably reproduce the bug now - there's a race condition occurring when saving answers or gradings under certain conditions.

**Comment by jiachen247** [comment]
https://github.com/source-academy/cadet/pull/517

^ this is a quick fix on the backend by extending the lifetime of the access token!
Gonna leave this issue open and we should definitely explore a cleaner solution on the frontend in winter when we have the time! Thanks for raising this @chrisgzf

**Comment by chrisgzf** [comment]
Hello! Just want to leave a note here for future reference that despite https://github.com/source-academy/cadet/pull/517, this issue occured during the PA to me and some other students who took the test in the same programming lab. If cadet and cadet-frontend is going to be used in the future, we should try to fix this again.
