### ISSUE TITLE
Reflect source level in assessments

### ISSUE THREAD

**Issue by jiachen247** [source-academy/cadet-frontend#953]
Currently theres really no way for students and even avengers to know which source level is being used for the different assessments.

**Comment by seanlowjk** [comment]
Just to clarify: By Assessments do we mean only the following?

1. Contests 
2. Missions 
3. Quests

**Comment by martin-henz** [comment]
At the moment, we have about five different kinds of assessments: Contests, Missions, Quests, Paths and Practicals.

**Comment by seanlowjk** [comment]
Alright, thanks Prof

**Comment by seanlowjk** [comment]
![image](https://user-images.githubusercontent.com/42912708/82292030-a3e88180-99dc-11ea-9594-3ecf91761d37.png)

For now, a simple implementation were to be to put  the associated chapter and external library for every question into a new tab. 

I am not sure if this requirement were to be alright?

**Comment by martin-henz** [comment]
Yes, thats a possible design. I'd like to propose that we put the Source §x in the place where it usually is, but as a fixed item, not as a dropdown menu. that way we can make use of the place that the library already occupies in the mental map of the user.

Also note that we will get rid of "external libraries". Instead, we will explicitly import the required library in the template on the right.

**Comment by seanlowjk** [comment]
Alright!

**Comment by seanlowjk** [comment]
![image](https://user-images.githubusercontent.com/42912708/82299894-ac46b980-99e8-11ea-82dd-bf9be60a672f.png)
 
Users should now be able to see the associated source chapter on the top left hand corner as mentioned
