### ISSUE TITLE
Error Message: [object Object] if streams are not checked if they are null

### ISSUE THREAD

**Issue by chrisgzf** [source-academy/cadet-frontend#963]
Hi, I encountered `Line 359: [object Object]` while doing the path on streams. Think this error message needs to be fixed to be more informative.

Not exactly sure which function triggered the error message, but will tell you how to reproduce the error.

If you don't check for `null` while manipulating finite streams
![image](https://user-images.githubusercontent.com/4933577/67082351-901d3880-f1cb-11e9-8e0c-cefd1e831799.png)

Then I tried to troubleshoot the thing by adding `enable verbose;`, but this completely breaks the code.

![image](https://user-images.githubusercontent.com/4933577/67082606-091c9000-f1cc-11e9-9bcc-5d95c3454541.png)

I fixed it by checking for `null` on finite streams.

![image](https://user-images.githubusercontent.com/4933577/67082661-2b161280-f1cc-11e9-92f9-757465589864.png)

Code to reproduce error [(playground link)](https://sourceacademy.nus.edu.sg/playground#chap=3&exec=1000&ext=NONE&prgrm=GYVwdgxgLglg9mABAWwIYGsCmB9VAbKTAJzFVjAHNsBnKIzVZAClvsYEpEBvAKEX8T0oIEogAOqGESYALBgBMWdBsnYAaRE04BeAHwoMOfIRJkYlGssZM%2BAu-YeOnDsJgpkcAdxlw8OVio2zsEhofwBjNhQknhKbKrsiQDcPAC%2BPDygkLAIiK7uhNjevv5WzBGq3Lb8QiJIElJMALRyqIoV6po6%2BvkeRT5%2BlvFxKlExIxzJaRkA9DOIACIA8ogAcksAKogAogsAkhsAXDwQCLSICJjUiNriktIAjBpaN-qX1OwpmABu%2BEOBaCwuAIxFI5CoFSYmDAIGQ-2sT0QAE5EhoUUkgA):
```javascript
function make_alternating_stream(stream) {
    return pair(head(stream), () => make_alternating_stream(
                                        negate_whole_stream(
                                            stream_tail(stream))));
}

function negate_whole_stream(stream) {
    return pair(-head(stream), () => negate_whole_stream(stream_tail(stream)));
}

// DO NOT EDIT:
const ones = pair(1, () => ones);
eval_stream(make_alternating_stream(enum_stream(1, 9)), 9);
```

Hope this helps!

**Comment by openorclose** [comment]
Thanks! It should be fixed here: https://github.com/source-academy/js-slang/pull/362
