### ISSUE TITLE
ENV: Pairs are drawn as ⚠️

### ISSUE THREAD

**Issue by angelsl** [source-academy/cadet-frontend#964]
```
const x = pair(1, 1);
display(x); // Breakpoint on this line
```

results in

![image](https://user-images.githubusercontent.com/235432/67139187-cfa55c80-f27f-11e9-9c8c-cc97d6d09b2f.png)

**Comment by martin-henz** [comment]
Yes, this is a limitation of the current environment visualizer. It it not yet integrated with the data visualizer. Every pair is currently drawn as a triangle, to indicate the issue.

**Comment by martin-henz** [comment]
subsumed by https://github.com/source-academy/cadet-frontend/issues/605
