### ISSUE TITLE
ENV: Fails entirely if it has to draw a function defined in a loop

### ISSUE THREAD

**Issue by angelsl** [source-academy/cadet-frontend#965]
```
let b = null;
while (b === null) {
    b = () => 1;
}
display(b); // Breakpoint here
```

```
let b = null;
for (let i = 0; i < 1; i = i + 1) {
    b = () => 1;
}
display(b); // Breakpoint here
```

No diagram is drawn when the breakpoint is hit. (No console error either. Are errors being swallowed?)

@thomastanck

**Comment by martin-henz** [comment]
The example program: https://sourceacademy.nus.edu.sg/playground#chap=3&exec=1000&ext=NONE&prgrm=DYUwLgBARhC8EDsCuxgG4BQB3AFgS1AgAoZYzEVgBKCAbwwkejmJtgD4IBGTAXwwwATPAGcADsACGATxJU0EARiA

<img width="284" alt="Screenshot 2020-02-25 at 9 33 38 AM" src="https://user-images.githubusercontent.com/30220768/75206675-f6d1e480-57b1-11ea-8559-9e37f5868a03.png">

**Comment by angelsl** [comment]
This issue no longer occurs.
