### ISSUE TITLE
Staging site sets navigator.mediaDevices to undefined

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet-frontend#978]
## Issue
As per the [API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)

> getUserMedia() is a powerful feature which can only be used in secure contexts; in insecure contexts, navigator.mediaDevices is undefined, preventing access to getUserMedia(). A secure context is, in short, a page loaded using HTTPS or the file:/// URL scheme, or a page loaded from localhost.

This means that the pix&flix library and machine library will not work on staging site.

## Suggested solution
Deliver staging site over secure connection (HTTPS)

**Comment by angelsl** [comment]
I'm in the midst of getting HTTPS for staging: https://stg.sourceacademy.nus.edu.sg

Currently waiting for SoC side to issue a TLS certificate for the stg subdomain. (If you click the link, it will complain of an invalid certificate currently.)

**Comment by jiayushe** [comment]
HTTPS has been configured.
