### ISSUE TITLE
Default Source version in Playground

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#981]
Proposal: The overall default should be: Source §4

The default can be modified by:
* setting the version explicitly in the Playground
* setting the version in the query string (URL parameter)
* setting the version explicitly in the mission XML (done by the mission authors)

**In addition, the system-wide default should be set to the version of the latest mission that is _Open_ in the system (if there is any mission released).**

**Comment by martin-henz** [comment]
This was in the scope of CP3108 Staff Dashboard and may already be merged. Can someone confirm this so that we can close this issue?

**Comment by seanlowjk** [comment]
This issue can be closed as the feature is working as intended.
