### ISSUE TITLE
Grading: "save changes" might miss on the first try

### ISSUE THREAD

**Issue by SwampertX** [source-academy/cadet-frontend#985]
This bug is not deterministic, but throughout grading for the semester, I have encountered this behaviour in more than half of the missions I graded.

**Steps to reproduce**
1. Grade a new mission in a new tab.
1. Write some comments, and/or make adjustments to the marks.
1. Click "Save and continue".

**Observed**

![image](https://user-images.githubusercontent.com/17807016/68688897-86100f00-05aa-11ea-8638-b1a3070dba2e.png)

conflicting behaviour of:
- green banner saying my edit is submitted
- a prompt asking me whether to leave
- all changes in marks/comments are reset

My observation is that the changes are actually saved, despite the warning given. Clicking "cancel" and attempt to re-save the same section will overwrite any comments you made beforehand.

This behaviour is only observed when grading the first part of a mission. It never happened in any subsequent part before. Also I always open a new tab when grading a new mission, not sure if that information is relevant.

Browser: Firefox Nightly 72.0a1

**Comment by Aulud** [comment]
@SwampertX This is actually a manifestation of the same bug reported in issue #934, which results in the data displayed to the user becoming stale despite the POST request having succeeded. We have found a way to deterministically reproduce the bug, and a small change has been made to the backend to mitigate the impact of the issue.

A thorough fix however, would require a significant re-write of parts of the frontend that communicate with the backend, alongside large parts of the infrastructure.

**Comment by martin-henz** [comment]
Need to understand this better, to see how we can translate this into a requirement for journeyman-frontend.
