### ISSUE TITLE
Firefox: Using the REPL does not extend the editor's height

### ISSUE THREAD

**Issue by SwampertX** [source-academy/cadet-frontend#987]
This issue only occurs in Firefox. Taking the Chrome's behaviour as the intended behaviour

Problems:
Using the repl does not create a scrollable section; instead it extends the whole right half on the pages with editors. When height of right half > left half, the editor is cut off.
![image](https://user-images.githubusercontent.com/17807016/68820170-68839800-06c5-11ea-8590-e0f638b6f02a.png)

Steps to reproduce:
1. Create a program longer than screen height in the playground.
2. Extend the REPL by firing empty commands until it autoscrolls the page down.
3. The Ace counterpart on the left is empty, clickable but no text rendered.

I interpret the problem as this also - the height of the Ace editor panel is fixed to the height of the current browser window. Upon extending the height of the whole screen using the REPL on the right,
the Ace editor however does not extend.

Browser: Firefox Nightly 72.0a1

**Comment by angelsl** [comment]
The fix is to put `min-height: 0` in a few places. @Aulud will put in a PR soon.

> Taking the Chrome's behaviour as the intended behaviour

This is actually [a Chrome/ium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=927066#c39).
