### ISSUE TITLE
ENV: frame box a bit too narrow

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet-frontend#988]
Long strings fit, but their quotation marks dont:

<img width="465" alt="Screenshot 2019-12-10 at 10 31 34 AM" src="https://user-images.githubusercontent.com/30220768/70490387-28cf9500-1b39-11ea-9fcb-42cdbe156a74.png">

**Comment by travisryte** [comment]
Should I create a pull-request to master? I fixed the issue.
![image](https://user-images.githubusercontent.com/25708498/73131617-6cc71c80-4049-11ea-8769-23f871a151ce.png)
