### ISSUE TITLE
Lacking a meta description tag

### ISSUE THREAD

**Issue by ning-y** [source-academy/cadet-frontend#993]
As a result, the search result description for Source Academy on Google looks rather lackluster:

<div align='center'>
<img src='https://user-images.githubusercontent.com/22320312/72971570-e3bfa380-3e04-11ea-93fa-4740a2f8c22c.PNG'>
</div>

This can be fixed simply by adding a `meta` tag with name `description`. See example 2 [here](https://www.w3schools.com/tags/tag_meta.asp), or refer to Khan Academy's homepage for something more in-the-wild.

@martin-henz: Recommendations for the description text? We can always go with the same description as in the [Source Academy organisation on GitHub](https://github.com/source-academy): "Immersive experiential environment for learning programming, developed in the School of Computing at the National University of Singapore".

**Comment by martin-henz** [comment]
Yes, that's a good description. Nice catch @ning-y !
